import type { Locale } from "@/lib/i18n";
import type { MontrealPageContent } from "@/lib/montrealContent";
import pediatricEnvironmentHero from "@/img/generated/pediatric-environment-hero.webp";
import pediatricProviderPlanning from "@/img/generated/pediatric-provider-planning.webp";
import pediatricQuietActivity from "@/img/generated/pediatric-quiet-activity.webp";

export const kidFriendlyResearchHospitalContent: Record<Locale, MontrealPageContent> = {
  en: {
    title: "Kid-Friendly Research Hospital",
    description: "Explore a careful vision for kid-friendly research hospital environments shaped with healthcare providers and ice-hockey-inspired support.",
    keywords: ["kid-friendly research hospital", "children's research hospital environment", "ice-hockey-themed pediatric environment", "pediatric cancer community support"],
    eyebrow: "A community-supported vision",
    heading: "A kid-friendly research hospital environment inspired by ice hockey",
    introduction: "A child receiving care for pediatric cancer or another debilitating condition deserves to be seen as a whole person, not only as a patient. The Silver Guardian's vision explores how an independent organization could work with willing healthcare providers and community partners to support welcoming, ice-hockey-themed surroundings that respect clinical priorities, family needs, and the realities of serious illness.",
    imageLabel: "Welcoming ice-hockey-inspired pediatric environment",
    imageAlt: "Welcoming ice-hockey-inspired pediatric environment designed with children in mind",
    heroAsset: { src: pediatricEnvironmentHero, alt: "Welcoming provider-designed pediatric family lounge with subtle ice hockey details and accessible seating" },
    supportingImageAssets: [
      { src: pediatricQuietActivity, alt: "Child using a wheelchair and caregiver choosing a quiet activity in an accessible pediatric family space" },
      { src: pediatricProviderPlanning, alt: "Interdisciplinary team reviewing accessible materials and plans for a child-friendly pediatric environment" },
    ],
    sections: [
      {
        heading: "Why a kid-friendly research hospital environment matters",
        paragraphs: [
          "Serious illness can make a child's days feel unfamiliar and tightly controlled. Appointments, tests, treatment times, and waiting/recovery rooms may interrupt school, friendships, play, and family routines. A thoughtfully designed environment cannot remove those burdens or change a diagnosis, but it can acknowledge that children still need comfort, imagination, and inspiration to engage with the world around them. An ice hockey theme can offer familiar colors, stories, and activities without asking a child to pretend that treatment is easy.",
          "Disclaimer: the phrase kid-friendly research hospital describes an innovational goal, not a currently operating facility. The Silver Guardian does not currently claim to own or operate a hospital. It also does not conduct medical research or provide diagnosis, treatment, rehabilitation, or medical advice.",
        ],
      },
      {
        heading: "What ice hockey can mean for different children",
        paragraphs: [
          "An ice-hockey-inspired environment should be broader than hockey club branding or competition. Some children may enjoy the artistry of ice skating or connect with hockey mascots, scoreboards, equipment shapes, or the simple idea of being part of a supportive hockey community; others may relate to the grit and determination of ice hockey players as it relates to their own fight against pediatric cancer. Design could use playful wayfinding, flexible activity prompts, celebratory artwork, or quiet visual details. Nothing should require physical participation, knowledge of ice hockey, or loyalty to a particular club.",
          "That being said, it is especially important to take into consideration that energy, mobility, vision, hearing, cognition, and/or sensory tolerance may change during care. An engaging feature for one child may be tiring for another. A responsible concept therefore includes calm routes, seating, adjustable stimulation, wheelchair access, readable signs, and activities that can be enjoyed from different positions. Healthcare and accessibility professionals would determine what is suitable.",
        ],
        bullets: [
          "Optional experiences that never interfere with treatment or rest",
          "Active, quiet, and observation-based ways to participate",
          "Inclusive design for varied ages, abilities, languages, and sensory needs",
          "Clear separation between community support and clinical decision-making",
        ],
      },
      {
        heading: "Research space provides additional care and clarity",
        paragraphs: [
          "Research can involve laboratories, data systems, clinical studies and highly regulated work. A child-friendly public environment does not make a foundation a research institution, and an independent organization should not describe itself as conducting or overseeing research unless that role has been formally established. Researchers and healthcare organizations remain responsible for protocols, ethics review, informed consent, privacy, scientific standards and communication with participating families.",
          "The Silver Guardian's community role would remain separate from those responsibilities. It could support public understanding of a confirmed, provider-led project or help fund an approved non-clinical environmental element, subject to written terms. It would not collect medical records, recruit research participants, interpret findings or suggest that an ice hockey theme improves clinical outcomes. Families should receive research information only through the qualified organizations responsible for the work and through processes designed to protect voluntary, informed decisions.",
        ],
      },
      {
        heading: "How community and ice hockey organizations can contribute",
        paragraphs: [
          "Community participation can be useful when it responds to an approved need. Businesses, ice hockey players, artists, designers, accessibility advocates and ice hockey organizations may be able to contribute funding, expertise, materials or creative ideas. Their involvement would not make them healthcare providers or grant access to patients. Recognition should be proportionate and appropriate for children’s spaces, with the provider retaining control over privacy, brand use, installation and ongoing operations.",
          "The Silver Guardian can help connect that enthusiasm to a disciplined process. Its existing fundraising and hockey-related initiatives provide ways for supporters to learn about the broader mission while provider relationships develop. Contributions should be described accurately: support for an independent concept or a specifically confirmed project, never a guarantee that a hospital will be built or that a clinical result will follow. Transparent milestones allow supporters to understand what has and has not been approved.",
        ],
      },
      {
        heading: "An independent community role",
        paragraphs: [
          "The Silver Guardian does not own, operate, manage, direct or represent any hospital, clinic or healthcare provider. The organization has no authority over care, medical decisions, hospital programs or referrals. Every initiative described on this page is independent and should not be interpreted as a clinical service or hospital affiliation.",
          "This page presents a general vision for collaboration around kid-friendly, ice-hockey-themed pediatric environments. It does not announce a hospital construction project, property, healthcare-provider partnership, research program, architectural plan, or opening date. It does not accept patients, referrals, research participants, or applications for services. No healthcare organization is asked to endorse this description merely because its work relates to children or research.",
        ],
      },
    ],
    relatedHeading: "Explore the wider mission",
    relatedLinks: [
      { href: "/more-info/", label: "Review The Silver Guardian’s proposed roadmap", description: "See how the long-term vision is presented as a phased proposal rather than an operating hospital." },
      { href: "/fundraising/", label: "Learn about community fundraising", description: "Explore current ways supporters can strengthen the independent community mission." },
      { href: "/32-wishes/", label: "Explore 32 Wishes in 32 Cities", description: "Learn about the goal of creating hockey-related moments for children across North America." },
      { href: "/movement-therapy-center/", label: "Read about the movement concept", description: "Explore a developing idea for accessible artistic and competitive movement." },
    ],
    faqHeading: "Kid-friendly research hospital FAQ",
    faqs: [
      { question: "Does The Silver Guardian own or operate a research hospital?", answer: "No. The Silver Guardian does not own, operate, manage, direct or represent a hospital, clinic, research institution or healthcare provider." },
      { question: "Is a new hospital being built?", answer: "No construction project, site, architectural plan, provider agreement, capital campaign or opening date is announced on this page. It describes a long-term collaborative vision only." },
      { question: "What could The Silver Guardian do with a healthcare provider?", answer: "If a willing provider approved a defined project, The Silver Guardian could help organize community support for non-clinical, ice-hockey-inspired environmental elements under the provider’s rules and oversight." },
      { question: "Would the ice hockey theme be part of medical treatment or research?", answer: "No clinical benefit is claimed. An ice hockey theme would be an optional environmental and community-support element, separate from diagnosis, treatment, rehabilitation and research decisions." },
      { question: "Can families apply for care or a research study here?", answer: "No. This page is not a referral, admissions or research-recruitment service. Families should use the official processes of qualified healthcare and research organizations." },
      { question: "How would children’s privacy be protected?", answer: "Any confirmed provider-led activity would require clear consent, limited information access and the provider’s privacy rules. Families should not send medical records or treatment details through general Silver Guardian forms." },
    ],
    closingHeading: "Support a careful, child-centred conversation",
    closingText: "Learn about the proposed roadmap and current community initiatives, then follow confirmed updates as The Silver Guardian explores whether qualified healthcare and community organizations want to shape this vision responsibly.",
    ctaLabel: "Review the proposed roadmap",
    ctaHref: "/more-info/",
  },
  "fr-CA": {
    title: "Hôpital de recherche pour enfants",
    description: "Découvrez une vision prudente d’un milieu de recherche pédiatrique créé avec des fournisseurs de soins et inspiré du hockey sur glace.",
    keywords: ["hôpital de recherche adapté aux enfants", "milieu hospitalier pédiatrique", "environnement pédiatrique inspiré du hockey sur glace", "soutien cancer pédiatrique"],
    eyebrow: "Une vision soutenue par la communauté",
    heading: "Un milieu de recherche adapté aux enfants et inspiré du hockey sur glace",
    introduction: "Un enfant soigné pour un cancer pédiatrique ou une autre maladie invalidante mérite d’être considéré comme une personne entière, et non uniquement comme un patient. La vision de The Silver Guardian explore comment une fondation indépendante pourrait collaborer avec des fournisseurs de soins volontaires et des partenaires communautaires afin de soutenir des espaces accueillants inspirés du hockey sur glace, dans le respect des priorités cliniques et des besoins familiaux.",
    imageLabel: "Milieu pédiatrique accueillant inspiré du hockey sur glace",
    imageAlt: "Milieu pédiatrique inspiré du hockey sur glace et pensé pour les enfants",
    heroAsset: { src: pediatricEnvironmentHero, alt: "Salon familial pédiatrique accueillant, accessible et conçu avec de subtils éléments de hockey sur glace" },
    supportingImageAssets: [
      { src: pediatricQuietActivity, alt: "Enfant en fauteuil roulant et proche choisissant une activité calme dans un espace pédiatrique accessible" },
      { src: pediatricProviderPlanning, alt: "Équipe interdisciplinaire examinant les matériaux et plans accessibles d’un milieu adapté aux enfants" },
    ],
    sections: [
      { heading: "Pourquoi un milieu de recherche adapté aux enfants compte", paragraphs: ["Une maladie grave peut rendre les journées d’un enfant inconnues et très encadrées. Les rendez-vous, les examens, les traitements, l’attente et la récupération peuvent interrompre l’école, les amitiés, le jeu et les habitudes familiales. Un milieu réfléchi ne peut pas enlever ces difficultés ni modifier un diagnostic, mais il peut reconnaître que les enfants ont toujours besoin de choix, de réconfort, d’imagination et de façons personnelles d’interagir avec ce qui les entoure. Un thème de hockey sur glace peut offrir des couleurs, des histoires et des activités familières sans demander à l’enfant de performer ou de prétendre que les soins sont faciles.", "L’expression hôpital de recherche adapté aux enfants désigne ici un objectif d’aménagement, et non un établissement en activité. The Silver Guardian ne prétend pas posséder, construire, exploiter ni gérer un hôpital. L’organisme ne mène pas non plus de recherche médicale et ne fournit aucun diagnostic, traitement, conseil médical ou service de réadaptation. Son rôle possible est communautaire : écouter, mobiliser l’appui et explorer si des fournisseurs de soins souhaitent obtenir une aide indépendante pour des éléments non cliniques clairement définis."] },
      { heading: "Collaborer avec les fournisseurs de soins sans diriger les soins", paragraphs: ["Toute activité significative dans un milieu de santé doit commencer par le fournisseur. Les directions hospitalières, les cliniciens en pédiatrie, les équipes de prévention des infections, les spécialistes du milieu de l’enfant, les professionnels des installations, les experts en accessibilité et les familles conseillères connaissent les exigences de leur environnement. Si un fournisseur choisissait de collaborer, il établirait les autorisations, les normes de sécurité, les limites cliniques et les conditions opérationnelles. The Silver Guardian pourrait alors organiser l’appui communautaire autour d’une portée approuvée plutôt que d’imposer une conception ou de faire des promesses au nom du fournisseur.", "Cette distinction protège les enfants, les familles et le personnel. Une fondation peut recueillir des idées, présenter des organismes communautaires, soutenir un objectif de financement approuvé ou coordonner des contributions créatives inspirées du hockey sur glace, mais elle ne décide pas de ce qui convient à une aire de traitement. Elle ne peut influencer la recherche clinique, la sélection des patients, les recommandations ou les plans de soins. Chaque élément devrait être évalué quant à la vie privée, aux infections, à l’accessibilité, à l’entretien, aux effets sensoriels et aux besoins pratiques du milieu."] },
      { heading: "Ce qu’un thème de hockey sur glace peut signifier pour différents enfants", paragraphs: ["Un milieu inspiré du hockey sur glace devrait aller au-delà des marques de clubs de hockey ou de la compétition. Certains enfants aiment jouer au hockey sur glace ou le regarder; d’autres se reconnaissent dans la forme d’une patinoire, les bâtons, les rondelles, les masques de gardien, les tableaux de pointage ou l’idée de faire partie d’une foule encourageante. L’aménagement pourrait proposer une signalisation ludique, des activités souples, des œuvres célébrant l’effort ou de petits détails visuels apaisants. Rien ne devrait exiger une participation physique, une connaissance du hockey sur glace ou une préférence pour un club.", "Le choix devient particulièrement important lorsque l’énergie, la mobilité, la vision, l’audition, la cognition ou la tolérance sensorielle changent pendant les soins. Un élément stimulant pour un enfant peut fatiguer un autre. Un concept responsable prévoit donc des parcours calmes, des sièges, une stimulation réglable, un accès en fauteuil roulant, des panneaux lisibles et des activités accessibles dans différentes positions. Les professionnels de la santé et de l’accessibilité détermineraient ce qui convient. Le thème doit servir les enfants, sans transformer le milieu clinique en publicité."], bullets: ["Des expériences facultatives qui ne gênent jamais les soins ou le repos", "Des façons actives, calmes ou simplement visuelles de participer", "Une conception inclusive pour différents âges, capacités, langues et besoins sensoriels", "Une séparation claire entre l’appui communautaire et les décisions cliniques"] },
      { heading: "Les espaces de recherche exigent une prudence supplémentaire", paragraphs: ["La recherche peut comprendre des laboratoires, des systèmes de données, des études cliniques et du travail hautement réglementé. Un espace public adapté aux enfants ne transforme pas une fondation en établissement de recherche. Un organisme indépendant ne devrait pas affirmer qu’il mène ou supervise des recherches sans rôle officiellement établi. Les chercheurs et les organismes de santé demeurent responsables des protocoles, de l’éthique, du consentement éclairé, de la vie privée, des normes scientifiques et des communications avec les familles participantes.", "Le rôle communautaire de The Silver Guardian resterait distinct de ces responsabilités. L’organisme pourrait soutenir la compréhension d’un projet confirmé et dirigé par un fournisseur ou contribuer au financement d’un élément non clinique approuvé, selon des modalités écrites. Il ne recueillerait pas de dossiers médicaux, ne recruterait pas de participants, n’interpréterait pas les résultats et ne laisserait pas entendre qu’un thème du hockey sur glace améliore les résultats cliniques. Les familles doivent recevoir l’information sur la recherche des organismes qualifiés responsables du travail."] },
      { heading: "Un parcours prudent, de l’idée au milieu approuvé", paragraphs: ["Les bonnes intentions ne sont qu’un point de départ. Une collaboration crédible exigerait un fournisseur défini, une portée écrite, des responsables identifiés, un budget réaliste et un plan d’entretien à long terme. Les premières discussions devraient préciser qui prend chaque décision et quelles déclarations peuvent être publiques. Les enfants et les proches devraient pouvoir expliquer ce qui les encourage, les déroute, les surcharge ou leur semble inaccessible, sans servir de témoignages ni devoir révéler des renseignements médicaux privés.", "La conception suivrait ensuite le processus d’examen établi par le fournisseur. Les matériaux, les fonctions numériques, le mobilier, les œuvres et les activités peuvent soulever des questions distinctes de sécurité et d’entretien. Un prototype peut aider à évaluer un concept avant son utilisation élargie. Les échéanciers doivent rester souples, puisque les activités cliniques sont prioritaires. Aucun élément, partenaire, lieu ou calendrier ne devrait être annoncé avant les approbations nécessaires et une compréhension claire des responsabilités."] },
      { heading: "La vie privée, la dignité et le choix familial d’abord", paragraphs: ["Les enfants qui reçoivent des soins ne devraient jamais devenir du matériel promotionnel parce qu’un organisme communautaire a soutenu un espace. La photographie, les récits, les affichages de reconnaissance et les événements exigent l’autorisation du fournisseur et un choix familial éclairé. Refuser la publicité ne doit jamais modifier l’accès aux soins ou à une activité approuvée. Les nouvelles publiques peuvent décrire l’objectif, le processus et l’espace achevé sans identifier les patients ni laisser entendre qu’un enfant représente toutes les familles.", "Le traitement de l’information exige des limites aussi fermes. The Silver Guardian n’a pas besoin du dossier médical d’un enfant pour présenter cette vision ou inviter un appui général. Tout futur programme exigeant des renseignements personnels nécessiterait une raison précise, des systèmes sécurisés, un accès limité, des règles de conservation et un consentement clair conçu avec l’organisme de santé responsable. Tant qu’un tel processus n’est pas officiellement annoncé, les familles ne devraient transmettre aucun diagnostic, détail de traitement ou document médical par courriel, formulaire général ou média social."] },
      { heading: "Comment la communauté et les organismes de hockey sur glace pourraient contribuer", paragraphs: ["La participation communautaire est utile lorsqu’elle répond à un besoin approuvé. Des entreprises, des joueurs et joueuses de hockey sur glace, des artistes, des concepteurs, des défenseurs de l’accessibilité et des organismes de hockey sur glace pourraient offrir du financement, de l’expertise, des matériaux ou des idées créatives. Leur participation ne ferait pas d’eux des fournisseurs de soins et ne leur donnerait aucun accès aux patients. La reconnaissance devrait rester proportionnée et convenir à un espace pour enfants, tandis que le fournisseur conserverait le contrôle sur la vie privée, les marques, l’installation et les opérations.", "The Silver Guardian peut aider à relier cet enthousiasme à un processus discipliné. Ses initiatives actuelles de financement et de souhaits liés au hockey permettent de découvrir la mission élargie pendant le développement de relations avec des fournisseurs. Toute contribution doit être décrite exactement : appui à un concept indépendant ou à un projet expressément confirmé, jamais garantie qu’un hôpital sera construit ou qu’un résultat clinique suivra. Des étapes transparentes permettent de comprendre ce qui est approuvé et ce qui ne l’est pas."] },
      { heading: "Ce que cette page annonce — et ce qu’elle n’annonce pas", paragraphs: ["Cette page présente une vision générale de collaboration autour de milieux pédiatriques adaptés aux enfants et inspirés du hockey sur glace. Elle n’annonce aucun projet de construction hospitalière, terrain, partenariat avec un fournisseur de soins, programme de recherche, campagne de financement, plan architectural ou date d’ouverture. Elle n’accepte aucun patient, recommandation, participant à la recherche ou demande de service. Aucun organisme de santé n’est présenté comme appuyant cette description simplement parce que son travail concerne les enfants ou la recherche.", "La prochaine étape responsable est la discussion et la vérification diligente. Des fournisseurs potentiels et des organismes communautaires peuvent évaluer si le concept répond à un besoin réel, puis définir une portée étroite et réalisable avant de demander un appui public. Les familles et les sympathisants peuvent suivre les mises à jour vérifiées et découvrir les initiatives communautaires actuelles. Séparer les aspirations des activités confirmées permet à une future collaboration de se développer sans créer des attentes que la fondation ne peut pas encore satisfaire."] },
    ],
    relatedHeading: "Découvrir la mission élargie",
    relatedLinks: [
      { href: "/more-info/", label: "Consulter la feuille de route proposée", description: "Voyez comment la vision à long terme est présentée comme une proposition par étapes plutôt que comme un hôpital en activité." },
      { href: "/fundraising/", label: "Découvrir le financement communautaire", description: "Explorez les façons actuelles de renforcer la mission communautaire indépendante." },
      { href: "/32-wishes/", label: "Découvrir 32 souhaits dans 32 villes", description: "Découvrez l’objectif de créer des moments liés au hockey pour des enfants en Amérique du Nord." },
      { href: "/movement-therapy-center/", label: "Lire sur le concept de mouvement", description: "Explorez une idée en développement axée sur le mouvement artistique et compétitif accessible." },
    ],
    faqHeading: "FAQ sur l’hôpital de recherche adapté aux enfants",
    faqs: [
      { question: "The Silver Guardian possède-t-il ou exploite-t-il un hôpital de recherche?", answer: "Non. The Silver Guardian ne possède, n’exploite, ne gère, ne dirige et ne représente aucun hôpital, clinique, établissement de recherche ou fournisseur de soins." },
      { question: "Un nouvel hôpital est-il en construction?", answer: "Non. Cette page n’annonce aucun chantier, terrain, plan architectural, accord avec un fournisseur, campagne de financement ni date d’ouverture. Elle décrit uniquement une vision collaborative à long terme." },
      { question: "Que pourrait faire The Silver Guardian avec un fournisseur de soins?", answer: "Si un fournisseur volontaire approuvait un projet défini, The Silver Guardian pourrait organiser l’appui communautaire pour des éléments non cliniques inspirés du hockey sur glace, selon les règles et la supervision du fournisseur." },
      { question: "Le thème du hockey sur glace ferait-il partie d’un traitement ou de la recherche?", answer: "Aucun avantage clinique n’est revendiqué. Un thème du hockey sur glace serait un élément facultatif du milieu et de l’appui communautaire, distinct du diagnostic, du traitement, de la réadaptation et des décisions de recherche." },
      { question: "Les familles peuvent-elles demander des soins ou participer à une étude ici?", answer: "Non. Cette page n’est pas un service de recommandation, d’admission ou de recrutement pour la recherche. Les familles doivent utiliser les processus officiels des organismes qualifiés." },
      { question: "Comment protégerait-on la vie privée des enfants?", answer: "Toute activité confirmée et dirigée par un fournisseur exigerait un consentement clair, un accès limité aux renseignements et le respect des règles de vie privée du fournisseur. Les familles ne devraient transmettre aucun dossier médical par les formulaires généraux de The Silver Guardian." },
    ],
    closingHeading: "Soutenir une conversation prudente centrée sur l’enfant",
    closingText: "Découvrez la feuille de route proposée et les initiatives communautaires actuelles, puis suivez les mises à jour confirmées pendant que The Silver Guardian explore si des organismes qualifiés souhaitent façonner cette vision de manière responsable.",
    ctaLabel: "Consulter la feuille de route proposée",
    ctaHref: "/more-info/",
  },
};
