import type { Locale } from "@/lib/i18n";
import type { GeoPageContent } from "@/lib/geoPageContent";
import pediatricEnvironmentHero from "@/img/generated/pediatric-environment-hero.webp";
import cancerTreatment from "@/img/cancertreatmentstockphoto2.jpg";
import hockeyArena from "@/img/hockey arena stock photo.jpg";
import hockeyHero from "@/img/hockey-hero-rising-stockcake.jpg";

const hockeyEnvironmentSections = {
  en: [
    ["Artistically Competitive", "Ice hockey is very similar to the fight against life-threatening illness, such as pediatric cancer or heart disease, because it requires artistry in designing early detection methods and innovative treatment plans, while simultaneously requiring patients to fight for their lives every day emotionally, mentally, and physically. No two journeys look the same, especially when it comes to cancer. Sometimes, patients will look like artistic skaters handling the journey with grace and agility, while others will look like determined competitors showing up every day to fight for themselves, their loved ones, and their fellow patients in their journey to survive."],
    ["Graceful Speed", "In ice hockey, when a player is aware of his surroundings, movement up and down the ice can be generated with graceful speed. Likewise, awareness of signs and symptoms of life-threatening illness, such as pediatric cancer or heart disease, is essential in assessing and addressing these conditions with graceful speed."],
    ["Agile Mobility", "Ice hockey players are some of the most agile athletes on the face of the planet, both mentally and physically, because in order to play the sport, they have to learn an entirely different mode of transportation, then learn the sport strategy in addition to that. The players who master this skill can utilize that agile mobility to fake out defenders, score incredibly beautiful goals, and execute precision passes to assist other teammates in scoring goals. Patients battling life-threatening illness, such as pediatric cancer or heart disease, often are forced to learn new modes of transportation to navigate through life, at least temporarily. With the right equipment and environment, patients can be encouraged to harness that new mode of transportation to pull off dazzling moves on their journey, allowing them to score incredible goals of survival and assist their fellow patients with precision inspiration every step of the way."],
    ["Balancing Act", "An essential part of ice hockey is balancing on a 3 to 4 millimeter piece of steel to glide around the ice surface. Patients battling life-threatening illness, such as pediatric cancer or heart disease, have to exercise the same balance when their world is completely altered by such a diagnosis. Patients are asked to balance treatment plans with school, work, rest, and everyday life. The right supportive, morale boosting environment can make this learning process feel less daunting, and empower patients to be successful on their journey."],
    ["Stopping power", "When ice hockey players stay alert, they possess the incredible ability to stop and turn away from obstacles that are in their path, even when they are skating at full speed. Similarly, early detection of life-threatening illness, such as pediatric cancer or heart disease, can provide patients with incredible stopping power, allowing them the opportunity to avoid debilitating obstacles in their way. Therefore, a kid friendly, ice hockey themed research environment must make education about early detection methods a priority without sacrificing the importance of researching more effective treatment plans for after the illness is properly identified."],
    ["Gritty Determination", "Not all hockey players are nimble skaters or flashy goal scorers, some are highly valued for their willingness to battle for possession of the puck in difficult areas along the walls of the rink with grit and determination, even if that means simultaneously having to fend off three or four different opponents who are also trying to possess the puck. Not all patients get the luxury of battling a life-threatening illness that was diagnosed through early detection, in which case the journey is never pretty or flashy, and even if the illness was detected early, there’s never a guarantee that a relapse will be detected early. It will require patients to battle every day for survival, sometimes in the hard areas with multiple obstacles trying to stop them. Our vision for a kid friendly, ice hockey themed research facility is important to boost morale for these brave individuals, and make sure that their every day battles do not go unnoticed or unappreciated. Note: Even in a supportive, morale boosting environment such as this, patients are allowed to feel tired, worried, or frustrated, but are always encouraged to persevere with grit and determination."],
    ["Warrior Mentality", "They call it the Identity Line, a group of players who show up every day like faithful warriors to compete for loose pucks, take a hit to make a play, and be the unsung heroes that anchor a championship hockey team. Some patients will look more like this kind of player, rather than a goal scorer or an assist machine, and every day, a hockey themed environment will allow the message “We see you, We appreciate you” to be heard loud and clear to all those patients who fight every day whether they make the highlight reel or not."],
    ["Resilient Competition", "In North American professional ice hockey, it takes winning 16 out of a potential 28 games to win the championship. Not all players will succeed, but every player that earns the opportunity to compete in that tournament battles to the end with incredible resiliency, in spite of great pain and hardship along the way. While patients do not ask to participate in a battle against life-threatening illness, such as pediatric cancer or heart disease, they should always be encouraged to fight to the end with incredible resiliency in spite of great and painful difficulty, no matter the outcome. Note: One of the great traditions at the end of every stage of the tournament is the handshake line where everyone has a chance to celebrate the effort it took to get to that point, so whether they succeed in hoisting the trophy or not, patients should always be commemorated and validated for resiliently competing to the end."],
    ["Friendly Neighborhood Mascots", "In sports, a welcoming and endearing mascot can make the game experience memorable and lead to a lot of positive memories for fans and players alike. The same is true in ice hockey, and in our kid-friendly research environment, these mascots would play a key role in boosting the morale of patients and staff."],
    ["Laughter", "Nothing quite compares to the zany antics of a favorite hockey mascot to make fans and players laugh with joy. The fight against life-threatening illness, such as pediatric cancer or heart disease, is filled with many negative emotions, but positive laughter can fill a treatment area with joy, and offer a welcome break from clinical routines."],
    ["Enthusiasm", "Depression is all too familiar for patients fighting life-threatening illness, such as pediatric cancer or heart disease, however, a well-timed visit by a favorite, enthusiastic hockey mascot can brighten even the darkest of days with fun-filled memories."],
    ["Teamwork", "A favorite hockey mascot embodies team spirit. Whether that’s dancing to energize the crowd, shooting T-Shirts out of a cannon, or driving the visiting team crazy, the mascot is focused on supporting the home team, no matter what. It is this team spirit energy that can make a kid-friendly hockey themed research environment so supportive for the patients that enter, whether the mascot is a big teddy bear handing out free hugs or a favorite staff member that makes a patient smile whenever they walk into the room."],
    ["Impressive Arenas", "True, ice hockey can be played on frozen backyard ponds or in community skating rinks, but nothing quite compares to the experience of visiting the splendorous venue of a professional team, regardless of the outcome of the game. While a clinical research environment is not one that people typically want to visit, when they do, it should inspire respect and boost morale regardless of the outcome, just like a well designed professional ice hockey venue."],
    ["Vocalized Support", "The best arenas have the best staff who care for your every need with a smile on their face. Caring for patients with life-threatening illness, such as pediatric cancer or heart disease, can be filled with both joy and grief, sometimes on the same day or in the same hour, so an innovative environment focused on boosting morale for patients can also make the workplace more fun for staff members, thus increasing the quality of care received by all around them. Don’t forget, staff members are patients too."],
    ["Home Ice Advantage", "For some patients, their journey means spending long periods of time away from the comforts of home. The kid-friendly, ice hockey themed research environment would include on-site housing that would be available to accommodate qualifying patients and staff to help boost morale by providing a “home ice advantage” while they fight life-threatening illness such as pediatric cancer or heart disease."],
    ["Practice Makes a Difference", "The most important part of the hockey game is what happens before the referee drops the puck…it’s the skills practiced during warm-ups and behind the scenes that make all the difference. Not all patients battling life-threatening illness are considered research cases, but every case can provide valuable research insight. Remember, a life-threatening illness is never a “typical case” for patients, and every lesson learned can save a person’s life."],
    ["Did Someone Say Food?", "One of the most memorable things about impressive sports venues is the wide variety of foods that are available, especially venues that like to highlight regional cuisine such as bbq and poutine. While hospitals are typically not known for their cuisine, our kid-friendly, ice hockey themed research environment would prioritize having delicious food available to patients and staff, without sacrificing nutrition or neglecting care plans. Note: According to Here To Serve, Inc. in Los Angeles, CA, 60% of the battle against cancer happens at home, so it is important to do our part to make sure that patients not only receive nutritious meals in a clinical facility, but also when they get home after many long hours of treatment."],
    ["Equipment Matters", "The sport of ice hockey cannot be played without specialized equipment. The same can be said for patients battling life-threatening illness such as pediatric cancer or heart disease."],
    ["Rubber Pucks and Hockey Sticks", "The fundamental principle of ice hockey is to navigate a 3 inch rubber puck across a 200 foot, obstacle filled ice surface with a stick, so strong puck movement is critical to success. For every patient diagnosed with a life-threatening illness such as pediatric cancer or heart disease, a survival percentage is stated. The patient has to then take that percentage and navigate across an environment filled with obstacles in an attempt to either beat or increase the percentage, depending on the perspective. Like the hockey stick, a patient’s physical, emotional, and mental health is all they have to move the puck down the ice, so it is important that we give them every chance to succeed in skating all the way to the goal. A kid-friendly, ice hockey themed research environment can provide clinical care to safeguard physical health and boost morale to safeguard both emotional and mental health."],
    ["Clean Ice (Zamboni machines)", "In between ice hockey periods, one of the most important pieces of equipment utilized is the Zamboni machine. It cleans the ice surface to make sure game play can be at the highest quality at the start of every 20 minute period. Likewise, in a kid-friendly research environment, disciplined environmental care is essential to make sure that patients can receive treatment at the highest quality possible."],
  ],
  "fr-CA": [
    ["Artistique et compétitif", "Le hockey sur glace ressemble beaucoup au combat contre une maladie potentiellement mortelle, comme le cancer pédiatrique ou une maladie cardiaque, puisqu’il faut faire preuve de créativité pour concevoir des méthodes de dépistage précoce et des plans de traitement novateurs, tandis que les patients doivent simultanément lutter chaque jour pour leur vie sur les plans émotionnel, mental et physique. Aucun parcours ne se ressemble, particulièrement lorsqu’il s’agit du cancer. Certains patients ressemblent parfois à des patineurs artistiques qui traversent cette épreuve avec grâce et agilité, tandis que d’autres ressemblent à des compétiteurs déterminés qui se présentent chaque jour pour lutter pour eux-mêmes, leurs proches et les autres patients dans leur parcours vers la survie."],
    ["Vitesse gracieuse", "Au hockey sur glace, un joueur conscient de ce qui l’entoure peut se déplacer sur la patinoire avec une vitesse gracieuse. De la même façon, connaître les signes et les symptômes d’une maladie potentiellement mortelle, comme le cancer pédiatrique ou une maladie cardiaque, est essentiel pour évaluer et traiter rapidement ces affections."],
    ["Mobilité agile", "Les joueurs de hockey sur glace comptent parmi les athlètes les plus agiles qui soient, tant mentalement que physiquement, car ils doivent apprendre un tout nouveau mode de déplacement avant même d’assimiler la stratégie du sport. Ceux qui maîtrisent cette habileté peuvent utiliser leur mobilité agile pour déjouer les défenseurs, marquer des buts d’une grande beauté et effectuer des passes précises qui aident leurs coéquipiers à marquer. Les patients qui luttent contre une maladie potentiellement mortelle, comme le cancer pédiatrique ou une maladie cardiaque, doivent souvent apprendre, au moins temporairement, de nouvelles façons de se déplacer dans la vie. Avec le bon équipement et le bon environnement, ils peuvent être encouragés à maîtriser ce nouveau mode de déplacement pour accomplir des manœuvres éblouissantes au fil de leur parcours, marquer des buts remarquables vers la survie et inspirer avec précision les autres patients à chaque étape."],
    ["Question d’équilibre", "Une composante essentielle du hockey sur glace consiste à garder l’équilibre sur une lame d’acier de trois à quatre millimètres pour glisser sur la patinoire. Les patients qui luttent contre une maladie potentiellement mortelle, comme le cancer pédiatrique ou une maladie cardiaque, doivent trouver ce même équilibre lorsque leur monde est complètement bouleversé par un tel diagnostic. Ils doivent concilier les plans de traitement, l’école, le travail, le repos et la vie quotidienne. Un environnement adéquat, encourageant et axé sur le moral peut rendre cet apprentissage moins intimidant et donner aux patients les moyens de progresser dans leur parcours."],
    ["Pouvoir d’arrêt", "Lorsqu’ils demeurent vigilants, les joueurs de hockey sur glace possèdent l’incroyable capacité de s’arrêter et de contourner les obstacles qui se dressent devant eux, même lorsqu’ils patinent à pleine vitesse. De la même façon, le dépistage précoce d’une maladie potentiellement mortelle, comme le cancer pédiatrique ou une maladie cardiaque, peut donner aux patients un remarquable pouvoir d’arrêt et leur permettre d’éviter des obstacles invalidants. Un milieu de recherche adapté aux enfants et inspiré du hockey sur glace doit donc accorder la priorité à l’éducation sur les méthodes de dépistage précoce, sans négliger l’importance de rechercher des traitements plus efficaces une fois la maladie correctement identifiée."],
    ["Détermination tenace", "Les joueurs de hockey ne sont pas tous des patineurs agiles ou des marqueurs spectaculaires. Certains sont grandement appréciés pour leur volonté de se battre avec ténacité et détermination pour prendre possession de la rondelle dans les zones difficiles le long de la bande, même lorsqu’ils doivent affronter simultanément trois ou quatre adversaires qui la convoitent aussi. Les patients n’ont pas tous la chance de lutter contre une maladie potentiellement mortelle détectée précocement; leur parcours n’est alors jamais élégant ni spectaculaire. Même lorsque la maladie a été détectée tôt, rien ne garantit qu’une rechute le sera également. Les patients doivent lutter chaque jour pour survivre, parfois dans les zones difficiles, alors que de nombreux obstacles tentent de les arrêter. Notre vision d’un milieu de recherche adapté aux enfants et inspiré du hockey sur glace vise à soutenir le moral de ces personnes courageuses et à faire en sorte que leurs combats quotidiens ne passent ni inaperçus ni inestimés. Remarque : même dans un environnement encourageant et axé sur le moral comme celui-ci, les patients ont le droit de se sentir fatigués, inquiets ou frustrés, tout en étant encouragés à persévérer avec ténacité et détermination."],
    ["Mentalité de guerrier", "On l’appelle le trio identitaire : un groupe de joueurs qui se présentent chaque jour comme de fidèles guerriers pour disputer les rondelles libres, encaisser une mise en échec afin de réussir un jeu et devenir les héros méconnus qui ancrent une équipe championne. Certains patients ressembleront davantage à ce type de joueur qu’à un marqueur ou à une machine à passes. Chaque jour, un environnement inspiré du hockey transmettra haut et fort le message « Nous vous voyons, nous vous apprécions » à tous les patients qui luttent quotidiennement, qu’ils apparaissent ou non dans les faits saillants."],
    ["Compétition résiliente", "Dans le hockey sur glace professionnel nord-américain, il faut remporter 16 matchs sur un maximum possible de 28 pour gagner le championnat. Les joueurs ne réussiront pas tous, mais chacun de ceux qui obtiennent la chance de participer à ce tournoi lutte jusqu’au bout avec une résilience remarquable, malgré la douleur et les épreuves rencontrées. Bien que les patients ne demandent pas à participer à un combat contre une maladie potentiellement mortelle, comme le cancer pédiatrique ou une maladie cardiaque, ils devraient toujours être encouragés à lutter jusqu’au bout avec une résilience remarquable, malgré les grandes difficultés et la douleur, quelle que soit l’issue. Remarque : après chaque étape du tournoi, la traditionnelle poignée de main permet à tous de célébrer les efforts déployés pour arriver jusque-là. Qu’ils réussissent ou non à soulever le trophée, les patients devraient donc toujours être honorés et reconnus pour avoir fait preuve de résilience jusqu’au bout."],
    ["Mascottes amicales du quartier", "Dans le sport, une mascotte accueillante et attachante peut rendre l’expérience mémorable et créer de nombreux souvenirs heureux pour les partisans comme pour les joueurs. Il en va de même au hockey sur glace. Dans notre milieu de recherche adapté aux enfants, ces mascottes joueraient un rôle important pour soutenir le moral des patients et du personnel."],
    ["Rire", "Rien ne vaut les folies d’une mascotte de hockey bien-aimée pour faire rire de joie les partisans et les joueurs. Le combat contre une maladie potentiellement mortelle, comme le cancer pédiatrique ou une maladie cardiaque, s’accompagne de nombreuses émotions négatives, mais un rire bienfaisant peut remplir une aire de traitement de joie et offrir une pause bienvenue dans les routines cliniques."],
    ["Enthousiasme", "La dépression est malheureusement bien connue des patients qui luttent contre une maladie potentiellement mortelle, comme le cancer pédiatrique ou une maladie cardiaque. Toutefois, la visite au bon moment d’une mascotte de hockey enthousiaste et bien-aimée peut égayer même les journées les plus sombres en créant des souvenirs remplis de plaisir."],
    ["Travail d’équipe", "Une mascotte de hockey bien-aimée incarne l’esprit d’équipe. Qu’elle danse pour énergiser la foule, lance des chandails à l’aide d’un canon ou rende l’équipe visiteuse folle, elle se concentre sur le soutien à l’équipe locale, quoi qu’il arrive. Cette énergie collective peut rendre un milieu de recherche adapté aux enfants et inspiré du hockey très encourageant pour les patients qui y entrent, qu’elle provienne d’un gros ourson offrant des câlins ou d’un membre du personnel préféré qui fait sourire un patient chaque fois qu’il entre dans la pièce."],
    ["Arénas impressionnants", "Il est vrai que le hockey sur glace peut se jouer sur un étang gelé dans une cour ou dans une patinoire communautaire, mais rien ne se compare vraiment à l’expérience de visiter le splendide aréna d’une équipe professionnelle, peu importe l’issue du match. Un milieu de recherche clinique n’est généralement pas un endroit que les gens souhaitent visiter. Lorsqu’ils doivent s’y rendre, il devrait néanmoins inspirer le respect et soutenir le moral, quelle que soit l’issue, comme le fait un aréna professionnel de hockey sur glace bien conçu."],
    ["Soutien exprimé", "Les meilleurs arénas ont le meilleur personnel, qui répond à tous les besoins avec le sourire. Prendre soin de patients atteints d’une maladie potentiellement mortelle, comme le cancer pédiatrique ou une maladie cardiaque, peut apporter à la fois de la joie et du chagrin, parfois au cours de la même journée ou de la même heure. Un environnement novateur axé sur le moral des patients peut également rendre le milieu de travail plus agréable pour le personnel et ainsi améliorer la qualité des soins reçus par tous ceux qui l’entourent. N’oublions pas que les membres du personnel sont eux aussi des patients."],
    ["Avantage de la glace locale", "Pour certains patients, le parcours exige de passer de longues périodes loin du confort de leur foyer. Le milieu de recherche adapté aux enfants et inspiré du hockey sur glace comprendrait des logements sur place destinés aux patients et aux membres du personnel admissibles afin de soutenir leur moral en leur procurant un « avantage de la glace locale » pendant leur combat contre une maladie potentiellement mortelle, comme le cancer pédiatrique ou une maladie cardiaque."],
    ["La pratique fait une différence", "La partie la plus importante d’un match de hockey se déroule avant que l’arbitre laisse tomber la rondelle : ce sont les habiletés pratiquées pendant l’échauffement et en coulisses qui font toute la différence. Les patients qui luttent contre une maladie potentiellement mortelle ne sont pas tous considérés comme des cas de recherche, mais chaque cas peut fournir de précieux enseignements. Une maladie potentiellement mortelle n’est jamais un « cas typique » pour les patients, et chaque leçon apprise peut sauver une vie."],
    ["Quelqu’un a parlé de nourriture?", "L’un des aspects les plus mémorables des arénas impressionnants est la grande variété d’aliments qui y sont offerts, particulièrement dans les établissements qui mettent en valeur la cuisine régionale, comme le barbecue et la poutine. Les hôpitaux ne sont généralement pas reconnus pour leur cuisine, mais notre milieu de recherche adapté aux enfants et inspiré du hockey sur glace accorderait la priorité à des repas délicieux pour les patients et le personnel, sans sacrifier la nutrition ni négliger les plans de soins. Remarque : selon Here to Serve, Inc., à Los Angeles, en Californie, 60 % du combat contre le cancer se déroule à la maison. Il est donc important de faire notre part pour que les patients reçoivent des repas nutritifs non seulement dans un établissement clinique, mais aussi lorsqu’ils rentrent chez eux après de longues heures de traitement."],
    ["L’équipement compte", "Le hockey sur glace ne peut se jouer sans équipement spécialisé. Il en va de même pour les patients qui luttent contre une maladie potentiellement mortelle, comme le cancer pédiatrique ou une maladie cardiaque."],
    ["Rondelles de caoutchouc et bâtons de hockey", "Le principe fondamental du hockey sur glace consiste à faire progresser, à l’aide d’un bâton, une rondelle de caoutchouc de trois pouces sur une patinoire de 200 pieds remplie d’obstacles. Une bonne circulation de la rondelle est donc essentielle au succès. Chaque patient qui reçoit un diagnostic de maladie potentiellement mortelle, comme le cancer pédiatrique ou une maladie cardiaque, se voit communiquer un taux de survie. Il doit ensuite composer avec ce pourcentage et traverser un environnement rempli d’obstacles afin de le dépasser ou de l’améliorer, selon le point de vue. Comme le bâton de hockey, la santé physique, émotionnelle et mentale est tout ce dont le patient dispose pour faire progresser la rondelle sur la glace. Il importe donc de lui donner toutes les chances de réussir à patiner jusqu’au but. Un milieu de recherche adapté aux enfants et inspiré du hockey sur glace peut offrir des soins cliniques qui protègent la santé physique et soutenir le moral afin de protéger la santé émotionnelle et mentale."],
    ["Glace propre (surfaceuses Zamboni)", "Entre les périodes d’un match de hockey sur glace, la surfaceuse Zamboni est l’une des pièces d’équipement les plus importantes. Elle nettoie la glace afin que le jeu soit de la plus grande qualité possible au début de chaque période de 20 minutes. De la même façon, dans un milieu de recherche adapté aux enfants, un entretien rigoureux de l’environnement est essentiel pour que les patients puissent recevoir des traitements de la plus grande qualité possible."],
  ],
} satisfies Record<Locale, [string, string][]>;

const hockeyEnvironmentH2Headings = new Set([
  "Artistically Competitive",
  "Friendly Neighborhood Mascots",
  "Impressive Arenas",
  "Equipment Matters",
  "Artistique et compétitif",
  "Mascottes amicales du quartier",
  "Arénas impressionnants",
  "L’équipement compte",
]);

const createHockeyEnvironmentSections = (locale: Locale) =>
  hockeyEnvironmentSections[locale].map(([heading, paragraph]) => ({
    heading,
    ...(hockeyEnvironmentH2Headings.has(heading) ? {} : { headingLevel: 3 as const }),
    paragraphs: [paragraph],
  }));

export const kidFriendlyResearchHospitalContent: Record<Locale, GeoPageContent> = {
  en: {
    title: "Kid-Friendly Research Environment",
    description: "Explore a careful vision for kid-friendly research environments shaped with healthcare providers and ice-hockey-inspired support.",
    keywords: ["kid-friendly research hospital", "children's research hospital environment", "ice-hockey-themed pediatric environment", "pediatric cancer community support"],
    eyebrow: "A community-supported vision",
    heading: "A kid-friendly research environment inspired by ice hockey",
    introduction: "A child receiving care for pediatric cancer or another life-threatening condition such as heart disease deserves to be seen as a whole person, not simply as a patient. The Silver Guardian's vision explores how an independent organization can work with willing healthcare providers and community partners to support a welcoming, ice-hockey-themed care environment that respects clinical priorities, caregiver needs and the realities of life-threatening illness.",
    imageLabel: "Welcoming ice-hockey-inspired pediatric environment",
    imageAlt: "Welcoming ice-hockey-inspired pediatric environment designed with children in mind",
    heroAsset: { src: hockeyHero, alt: "Illustration of an ice hockey player handling a puck on fractured ice" },
    heroSecondaryAsset: { src: pediatricEnvironmentHero, alt: "Welcoming provider-designed pediatric family lounge with subtle ice hockey details and accessible seating" },
    supportingImageAssets: [
      { src: hockeyArena, alt: "Interior of a hockey arena with the rink illuminated beneath the seating" },
      { src: cancerTreatment, alt: "Caregiver talking with a child seated in a pediatric treatment room" },
    ],
    flowBanner: {
      beforeHeading: "Friendly Neighborhood Mascots",
      eyebrow: "Coming soon",
      title: "The Memory Wall",
      href: "https://cloud-screen.com/v2/publications/silver-guardian-memory-wall",
      linkLabel: "Explore the Memory Wall",
    },
    sections: [
      {
        heading: "Why a kid-friendly research hospital environment matters",
        paragraphs: [
          "Life-threatening illness, such as cancer or heart disease, can make a child's days feel unfamiliar, invaded and tightly controlled. Appointments, tests, treatment times and waiting rooms interrupt school, friendships, play, and family routines. A thoughtfully designed environment cannot completely remove those burdens or change a diagnosis; however, it can acknowledge that children still need comfort, imagination, and inspiration. An ice hockey theme can offer familiar colors, stories, and activities without asking a child to pretend that treatment is easy or fun.",
          "Disclaimer: the phrase kid-friendly research environment describes an innovational goal, not a currently operating facility. The Silver Guardian does not currently claim to own or operate a hospital. It also does not conduct medical research or provide diagnosis, treatment, rehabilitation, or medical advice.",
        ],
      },
      {
        heading: "What an ice hockey theme can mean for children facing life-threatening illness",
        paragraphs: [
          "A healthcare environment inspired by ice hockey should be broader than club branding or themed décor. Some patients may relate to the artistry of skating, the humor of mascots, the grandeur of arenas, the science of equipment or the camaraderie of teamwork; others may relate to players’ grit, determination and warrior mentality during their own experience with pediatric cancer, heart disease or another life-threatening condition. Knowledge of ice hockey, loyalty to a professional team, or physical ability to play the sport would never be prerequisites for care.",
          "Inspired play, flexible activities, celebratory artwork, or quiet visual details may inspire hope; however, energy level, mobility, vision, hearing, cognition, and sensory tolerance can or will change during treatment. An engaging feature for one patient may tire another. A responsible environment concept therefore includes calm support, adjustable stimulation, wheelchair access, clear signage, and engaging activities enjoyed from different perspectives under appropriate healthcare supervision.",
        ],
        bullets: [
          "Optional experiences that are balanced with treatment and rest",
          "Active, quiet, and observation-based ways to participate",
          "Innovative design for varied ages, abilities, languages, and sensory needs",
          "Clear separation between community support and clinical decision-making",
        ],
      },
      ...createHockeyEnvironmentSections("en"),
      {
        heading: "Research space provides additional care and clarity",
        paragraphs: [
          "Continued state-of-the-art pediatric cancer research is essential. The National Cancer Institute explains that progress remains limited for some childhood cancers, survivors can experience long-term effects and researchers need stronger collaboration and data sharing. The Children’s Cancer Research Fund has historically described childhood cancer research as receiving about 4% of federal cancer-research funding. That figure is a cited advocacy measure, not a claim that every cancer dollar is divided in the same way, but it illustrates why sustained public and philanthropic attention matters.",
          "Research infrastructure should not come at the expense of daily care beyond the clinic. Here to Serve reports that families spend more than 60% of a child’s cancer journey at home, often while carrying physical, emotional and financial burdens. The Silver Guardian’s vision therefore joins advanced research and clinical facilities with comfortable on-site housing and connections to qualified at-home resources so patients, caregivers, researchers and staff are considered as whole people.",
          "Research can involve laboratories, data systems, clinical studies and highly regulated work. Researchers and healthcare organizations would remain responsible for protocols, ethics review, informed consent, privacy, scientific standards and communication with participating families. The Silver Guardian would not collect medical records, recruit participants, interpret findings or claim that environmental themes improve clinical outcomes.",
        ],
        links: [
          { href: "https://www.cancer.gov/research/areas/childhood", label: "National Cancer Institute: Research on Childhood Cancers", description: "Review why continued research, collaboration and safer treatments remain necessary." },
          { href: "https://childrenscancer.org/about-us/what-we-fund/", label: "Children’s Cancer Research Fund: What We Fund", description: "See the source and context for the historical 4% federal funding statement." },
          { href: "https://heretoserve.org/mission-and-vision/", label: "Here to Serve: Mission and Vision", description: "Read the source for the statement that more than 60% of the cancer journey happens at home." },
        ],
      },
      {
        heading: "How community and ice hockey organizations can contribute",
        paragraphs: [
          "Community participation is essential and encouraged as a demonstration of support for children facing life-threatening conditions such as pediatric cancer and heart disease. Businesses, athletes, artists, designers, charitable foundations and ice hockey organizations may contribute funding, expertise, materials or creative ideas. Their involvement would not make them healthcare providers or grant unlimited access to patients and caregivers.",
          "Hospital leadership, patients, caregivers and licensed healthcare professionals would appropriately safeguard privacy and day-to-day activities. Recognition, branding, events, photography and access would remain subject to provider rules and informed family choices. Community support must strengthen an approved need without displacing care or implying a clinical result.",
        ],
      },
      {
        heading: "An independent organization",
        paragraphs: [
          "Kid-friendly research environment describes an innovative goal, not a currently operating facility. The Silver Guardian does not currently own or operate a hospital, conduct medical research or provide diagnosis, treatment, rehabilitation or medical advice. It does not manage, direct or represent a hospital, clinic or healthcare provider and has no authority over care, medical decisions, hospital programs or referrals.",
          "This page presents a general vision for collaboration around kid-friendly, ice-hockey-themed pediatric healthcare environments. No specific hospital construction project, property, healthcare-provider partnership, research program, architectural plan or opening date is confirmed or announced. Because The Silver Guardian does not provide clinical services, it does not accept medical referrals or applications for clinical services. Healthcare organizations are not obligated to endorse this vision merely because their work relates to pediatric care or cancer and cardiovascular research.",
        ],
      },
    ],
    relatedHeading: "Explore the wider mission",
    relatedLinks: [
      { href: "/more-info/", label: "Review The Silver Guardian’s proposed roadmap", description: "See how the long-term vision is presented as a phased proposal rather than an operating hospital." },
      { href: "/fundraising/", label: "Learn about community fundraising", description: "Explore current ways supporters can strengthen the independent community mission." },
      { href: "/32-wishes/", label: "Explore 32 Wishes in 32 Cities", description: "Learn about the goal of creating hockey-related moments for children across North America." },
      { href: "/movement-therapy-center/", label: "Read about the movement concept", description: "Explore a developing idea for accessible artistic and competitive movement." },
    ],
    faqHeading: "Kid-friendly research environment FAQ",
    faqs: [
      { question: "Does The Silver Guardian own or operate a research facility?", answer: "No. The Silver Guardian does not own, operate, manage, direct or represent a hospital, clinic, research institution, or healthcare provider." },
      { question: "Would the ice hockey theme be part of medical treatment or research?", answer: "No clinical benefit is claimed. An ice hockey theme helps to benefit the morale and wellbeing of patients in care." },
      { question: "Can families apply for care or a research study here?", answer: "No. This page is not a referral, admissions or research-recruitment service. Families should use the official processes of qualified healthcare and research organizations." },
      { question: "How would children’s privacy be protected?", answer: "Any confirmed provider-led activity would require clear consent, limited information access and the provider’s privacy rules. Families should not send medical records or treatment details through our general contact forms." },
    ],
    closingHeading: "Support a careful, child-centred conversation",
    closingText: "Learn about the proposed roadmap and current community initiatives, then follow confirmed updates as The Silver Guardian explores whether qualified healthcare and community organizations want to shape this vision responsibly.",
    ctaLabel: "Review the proposed roadmap",
    ctaHref: "/more-info/",
  },
  "fr-CA": {
    title: "Milieu de recherche adapté aux enfants",
    description: "Découvrez une vision prudente d’un milieu de recherche pédiatrique créé avec des fournisseurs de soins et inspiré du hockey sur glace.",
    keywords: ["hôpital de recherche adapté aux enfants", "milieu hospitalier pédiatrique", "environnement pédiatrique inspiré du hockey sur glace", "soutien cancer pédiatrique"],
    eyebrow: "Une vision soutenue par la communauté",
    heading: "Un milieu de recherche adapté aux enfants et inspiré du hockey sur glace",
    introduction: "Un enfant soigné pour un cancer pédiatrique ou une autre maladie potentiellement mortelle, comme une maladie cardiaque, mérite d’être considéré comme une personne entière et non simplement comme un patient. La vision de The Silver Guardian explore comment un organisme indépendant peut collaborer avec des fournisseurs volontaires et des partenaires communautaires pour soutenir un milieu de soins accueillant inspiré du hockey sur glace, dans le respect des priorités cliniques, des proches aidants et des réalités de la maladie.",
    imageLabel: "Milieu pédiatrique accueillant inspiré du hockey sur glace",
    imageAlt: "Milieu pédiatrique inspiré du hockey sur glace et pensé pour les enfants",
    heroAsset: { src: hockeyHero, alt: "Illustration d’un joueur de hockey sur glace maniant une rondelle sur une surface de glace fracturée" },
    heroSecondaryAsset: { src: pediatricEnvironmentHero, alt: "Salon familial pédiatrique accueillant, accessible et conçu avec de subtils éléments de hockey sur glace" },
    supportingImageAssets: [
      { src: hockeyArena, alt: "Intérieur d’un aréna de hockey avec la patinoire éclairée sous les gradins" },
      { src: cancerTreatment, alt: "Proche aidante discutant avec un enfant assis dans une salle de traitement pédiatrique" },
    ],
    flowBanner: {
      beforeHeading: "Mascottes amicales du quartier",
      eyebrow: "Bientôt disponible",
      title: "Le mur des souvenirs",
      href: "https://cloud-screen.com/v2/publications/silver-guardian-memory-wall",
      linkLabel: "Découvrir le mur des souvenirs",
    },
    sections: [
      { heading: "Pourquoi un milieu de recherche adapté aux enfants compte", paragraphs: ["Une maladie grave peut rendre les journées d’un enfant inconnues et très encadrées. Les rendez-vous, les examens, les traitements, l’attente et la récupération peuvent interrompre l’école, les amitiés, le jeu et les habitudes familiales. Un milieu réfléchi ne peut pas enlever ces difficultés ni modifier un diagnostic, mais il peut reconnaître que les enfants ont toujours besoin de choix, de réconfort, d’imagination et de façons personnelles d’interagir avec ce qui les entoure. Un thème de hockey sur glace peut offrir des couleurs, des histoires et des activités familières sans demander à l’enfant de performer ou de prétendre que les soins sont faciles.", "L’expression milieu de recherche adapté aux enfants désigne ici un objectif d’aménagement, et non un établissement en activité. The Silver Guardian ne prétend pas posséder, construire, exploiter ni gérer un hôpital. L’organisme ne mène pas non plus de recherche médicale et ne fournit aucun diagnostic, traitement, conseil médical ou service de réadaptation. Son rôle possible est communautaire : écouter, mobiliser l’appui et explorer si des fournisseurs de soins souhaitent obtenir une aide indépendante pour des éléments non cliniques clairement définis."] },
      { heading: "Collaborer avec les fournisseurs de soins sans diriger les soins", paragraphs: ["Toute activité significative dans un milieu de santé doit commencer par le fournisseur. Les directions hospitalières, les cliniciens en pédiatrie, les équipes de prévention des infections, les spécialistes du milieu de l’enfant, les professionnels des installations, les experts en accessibilité et les familles conseillères connaissent les exigences de leur environnement. Si un fournisseur choisissait de collaborer, il établirait les autorisations, les normes de sécurité, les limites cliniques et les conditions opérationnelles. The Silver Guardian pourrait alors organiser l’appui communautaire autour d’une portée approuvée plutôt que d’imposer une conception ou de faire des promesses au nom du fournisseur.", "Cette distinction protège les enfants, les familles et le personnel. Une fondation peut recueillir des idées, présenter des organismes communautaires, soutenir un objectif de financement approuvé ou coordonner des contributions créatives inspirées du hockey sur glace, mais elle ne décide pas de ce qui convient à une aire de traitement. Elle ne peut influencer la recherche clinique, la sélection des patients, les recommandations ou les plans de soins. Chaque élément devrait être évalué quant à la vie privée, aux infections, à l’accessibilité, à l’entretien, aux effets sensoriels et aux besoins pratiques du milieu."] },
      { heading: "Ce qu’un thème de hockey sur glace peut signifier pour différents enfants", paragraphs: ["Un milieu inspiré du hockey sur glace devrait aller au-delà des marques de clubs de hockey ou de la compétition. Certains enfants aiment jouer au hockey sur glace ou le regarder; d’autres se reconnaissent dans la forme d’une patinoire, les bâtons, les rondelles, les masques de gardien, les tableaux de pointage ou l’idée de faire partie d’une foule encourageante. L’aménagement pourrait proposer une signalisation ludique, des activités souples, des œuvres célébrant l’effort ou de petits détails visuels apaisants. Rien ne devrait exiger une participation physique, une connaissance du hockey sur glace ou une préférence pour un club.", "Le choix devient particulièrement important lorsque l’énergie, la mobilité, la vision, l’audition, la cognition ou la tolérance sensorielle changent pendant les soins. Un élément stimulant pour un enfant peut fatiguer un autre. Un concept responsable prévoit donc des parcours calmes, des sièges, une stimulation réglable, un accès en fauteuil roulant, des panneaux lisibles et des activités accessibles dans différentes positions. Les professionnels de la santé et de l’accessibilité détermineraient ce qui convient. Le thème doit servir les enfants, sans transformer le milieu clinique en publicité."], bullets: ["Des expériences facultatives qui ne gênent jamais les soins ou le repos", "Des façons actives, calmes ou simplement visuelles de participer", "Une conception inclusive pour différents âges, capacités, langues et besoins sensoriels", "Une séparation claire entre l’appui communautaire et les décisions cliniques"] },
      ...createHockeyEnvironmentSections("fr-CA"),
      { heading: "Les espaces de recherche ajoutent soins et clarté", paragraphs: ["La poursuite d’une recherche pédiatrique de pointe demeure essentielle. Le National Cancer Institute explique que les progrès restent limités pour certains cancers, que des survivants subissent des effets à long terme et que la collaboration et le partage des données doivent progresser. Le Children’s Cancer Research Fund a historiquement décrit la recherche sur le cancer pédiatrique comme recevant environ 4 % du financement fédéral de la recherche sur le cancer. Il s’agit d’une mesure militante citée, et non d’une répartition de tous les fonds, mais elle illustre le besoin d’un appui durable.", "L’infrastructure scientifique ne devrait pas faire oublier la vie hors clinique. Here to Serve indique que les familles passent plus de 60 % du parcours de cancer d’un enfant à la maison, avec des charges physiques, émotionnelles et financières. La vision associe donc des installations cliniques et scientifiques avancées à des logements confortables sur place et à des ressources qualifiées pour la maison, afin de considérer les patients, proches, chercheurs et membres du personnel comme des personnes entières.", "Les chercheurs et organismes de santé resteraient responsables des protocoles, de l’éthique, du consentement, de la vie privée et des normes scientifiques. The Silver Guardian ne recueillerait aucun dossier médical, ne recruterait aucun participant, n’interpréterait aucun résultat et ne revendiquerait aucun effet clinique du thème."], links: [
        { href: "https://www.cancer.gov/research/areas/childhood", label: "National Cancer Institute : recherche sur les cancers pédiatriques", description: "Découvrez pourquoi la recherche, la collaboration et des traitements plus sûrs restent nécessaires." },
        { href: "https://childrenscancer.org/about-us/what-we-fund/", label: "Children’s Cancer Research Fund : recherche financée", description: "Consultez la source et le contexte de l’énoncé historique de 4 %." },
        { href: "https://heretoserve.org/mission-and-vision/", label: "Here to Serve : mission et vision", description: "Consultez la source de l’énoncé selon lequel plus de 60 % du parcours se déroule à la maison." },
      ] },
      { heading: "Un parcours prudent, de l’idée au milieu approuvé", paragraphs: ["Les bonnes intentions ne sont qu’un point de départ. Une collaboration crédible exigerait un fournisseur défini, une portée écrite, des responsables identifiés, un budget réaliste et un plan d’entretien à long terme. Les premières discussions devraient préciser qui prend chaque décision et quelles déclarations peuvent être publiques. Les enfants et les proches devraient pouvoir expliquer ce qui les encourage, les déroute, les surcharge ou leur semble inaccessible, sans servir de témoignages ni devoir révéler des renseignements médicaux privés.", "La conception suivrait ensuite le processus d’examen établi par le fournisseur. Les matériaux, les fonctions numériques, le mobilier, les œuvres et les activités peuvent soulever des questions distinctes de sécurité et d’entretien. Un prototype peut aider à évaluer un concept avant son utilisation élargie. Les échéanciers doivent rester souples, puisque les activités cliniques sont prioritaires. Aucun élément, partenaire, lieu ou calendrier ne devrait être annoncé avant les approbations nécessaires et une compréhension claire des responsabilités."] },
      { heading: "La vie privée, la dignité et le choix familial d’abord", paragraphs: ["Les enfants qui reçoivent des soins ne devraient jamais devenir du matériel promotionnel parce qu’un organisme communautaire a soutenu un espace. La photographie, les récits, les affichages de reconnaissance et les événements exigent l’autorisation du fournisseur et un choix familial éclairé. Refuser la publicité ne doit jamais modifier l’accès aux soins ou à une activité approuvée. Les nouvelles publiques peuvent décrire l’objectif, le processus et l’espace achevé sans identifier les patients ni laisser entendre qu’un enfant représente toutes les familles.", "Le traitement de l’information exige des limites aussi fermes. The Silver Guardian n’a pas besoin du dossier médical d’un enfant pour présenter cette vision ou inviter un appui général. Tout futur programme exigeant des renseignements personnels nécessiterait une raison précise, des systèmes sécurisés, un accès limité, des règles de conservation et un consentement clair conçu avec l’organisme de santé responsable. Tant qu’un tel processus n’est pas officiellement annoncé, les familles ne devraient transmettre aucun diagnostic, détail de traitement ou document médical par courriel, formulaire général ou média social."] },
      { heading: "Comment la communauté et les organismes de hockey peuvent contribuer", paragraphs: ["La participation communautaire est essentielle et encouragée pour démontrer un appui aux enfants touchés par une maladie potentiellement mortelle comme le cancer ou une maladie cardiaque. Entreprises, athlètes, artistes, concepteurs, fondations caritatives et organismes de hockey peuvent contribuer du financement, de l’expertise, des matériaux ou des idées. Leur participation ne fait pas d’eux des fournisseurs de soins et ne leur donne aucun accès illimité aux patients et proches.", "La direction hospitalière, les patients, les proches et les professionnels autorisés protégeraient la vie privée et les activités quotidiennes. La reconnaissance, les marques, événements, photos et accès resteraient soumis aux règles du fournisseur et aux choix éclairés des familles."] },
      { heading: "Un organisme indépendant", paragraphs: ["Milieu de recherche adapté aux enfants décrit un objectif novateur, et non un établissement actif. The Silver Guardian ne possède ni n’exploite actuellement d’hôpital, ne mène aucune recherche médicale et n’offre aucun diagnostic, traitement, service de réadaptation ou conseil médical. Il ne gère, ne dirige et ne représente aucun hôpital, clinique ou fournisseur et n’a aucune autorité sur les soins, décisions médicales, programmes ou recommandations.", "Cette page présente une vision générale de collaboration autour de milieux pédiatriques inspirés du hockey. Aucun chantier précis, terrain, partenariat, programme de recherche, plan architectural ou date d’ouverture n’est confirmé. Puisque The Silver Guardian n’offre aucun service clinique, il n’accepte ni recommandation médicale ni demande de service. Aucun organisme de santé n’est tenu d’appuyer cette vision parce que son travail concerne les soins pédiatriques ou la recherche sur le cancer et les maladies cardiovasculaires."] },
    ],
    relatedHeading: "Découvrir la mission élargie",
    relatedLinks: [
      { href: "/more-info/", label: "Consulter la feuille de route proposée", description: "Voyez comment la vision à long terme est présentée comme une proposition par étapes plutôt que comme un hôpital en activité." },
      { href: "/fundraising/", label: "Découvrir le financement communautaire", description: "Explorez les façons actuelles de renforcer la mission communautaire indépendante." },
      { href: "/32-wishes/", label: "Découvrir 32 souhaits dans 32 villes", description: "Découvrez l’objectif de créer des moments liés au hockey pour des enfants en Amérique du Nord." },
      { href: "/movement-therapy-center/", label: "Lire sur le concept de mouvement", description: "Explorez une idée en développement axée sur le mouvement artistique et compétitif accessible." },
    ],
    faqHeading: "FAQ sur le milieu de recherche adapté aux enfants",
    faqs: [
      { question: "The Silver Guardian possède-t-il ou exploite-t-il un hôpital de recherche?", answer: "Non. The Silver Guardian ne possède, n’exploite, ne gère, ne dirige et ne représente aucun hôpital, clinique, établissement de recherche ou fournisseur de soins." },
      { question: "Un nouvel hôpital est-il en construction?", answer: "Non. Cette page n’annonce aucun chantier, terrain, plan architectural, accord avec un fournisseur, campagne de financement ni date d’ouverture. Elle décrit uniquement une vision collaborative à long terme." },
      { question: "Que pourrait faire The Silver Guardian avec un fournisseur de soins?", answer: "Si un fournisseur volontaire approuvait un projet défini, The Silver Guardian pourrait organiser l’appui communautaire pour des éléments non cliniques inspirés du hockey sur glace, selon les règles et la supervision du fournisseur." },
      { question: "Le thème du hockey sur glace ferait-il partie d’un traitement ou de la recherche?", answer: "Aucun avantage clinique n’est revendiqué. Un thème du hockey sur glace serait un élément facultatif du milieu et de l’appui communautaire, distinct du diagnostic, du traitement, de la réadaptation et des décisions de recherche." },
      { question: "Les familles peuvent-elles demander des soins ou participer à une étude ici?", answer: "Non. Cette page n’est pas un service de recommandation, d’admission ou de recrutement pour la recherche. Les familles doivent utiliser les processus officiels des organismes qualifiés." },
      { question: "Comment protégerait-on la vie privée des enfants?", answer: "Toute activité confirmée et dirigée par un fournisseur exigerait un consentement clair, un accès limité aux renseignements et le respect des règles de vie privée du fournisseur. Les familles ne devraient transmettre aucun dossier médical par les formulaires généraux de The Silver Guardian." },
    ],
    closingHeading: "Soutenir une conversation prudente centrée sur l’enfant",
    closingText: "Découvrez la feuille de route proposée et les initiatives communautaires actuelles, puis suivez les mises à jour confirmées pendant que The Silver Guardian explore si des organismes qualifiés souhaitent façonner cette vision de manière responsable.",
    ctaLabel: "Consulter la feuille de route proposée",
    ctaHref: "/more-info/",
  },
};
