import type { Locale } from "@/lib/i18n";
import type { MontrealPageContent } from "@/lib/montrealContent";

type CityKey = "laval" | "longueuil" | "brossard" | "terrebonne" | "pointe-claire";

const cityDetails: Record<CityKey, { name: string; areaEn: string; areaFr: string; travelEn: string; travelFr: string; communityEn: string; communityFr: string }> = {
  laval: { name: "Laval", areaEn: "neighbourhoods across Île Jésus", areaFr: "les quartiers de l’île Jésus", travelEn: "bridge traffic, Autoroutes 13, 15, 19 and 25, buses, the métro and winter conditions", travelFr: "les ponts, les autoroutes 13, 15, 19 et 25, les autobus, le métro et l’hiver", communityEn: "recreation centres, dance studios, accessible fitness organizations and community groups", communityFr: "les centres récréatifs, studios de danse, organismes de conditionnement adapté et groupes communautaires" },
  longueuil: { name: "Longueuil", areaEn: "Vieux-Longueuil, Saint-Hubert, Greenfield Park and the wider South Shore", areaFr: "le Vieux-Longueuil, Saint-Hubert, Greenfield Park et la Rive-Sud", travelEn: "Route 132, bridge traffic, métro and bus connections and winter travel", travelFr: "la route 132, les ponts, le métro, les autobus et les déplacements hivernaux", communityEn: "borough recreation programs, studios, schools and accessible activity organizations", communityFr: "les programmes récréatifs d’arrondissement, studios, écoles et organismes d’activité adaptée" },
  brossard: { name: "Brossard", areaEn: "Brossard’s multilingual neighbourhoods and nearby South Shore communities", areaFr: "les quartiers multilingues de Brossard et les communautés voisines de la Rive-Sud", travelEn: "Autoroutes 10, 15 and 30, REM and bus connections, parking and bridge congestion", travelFr: "les autoroutes 10, 15 et 30, le REM, les autobus, le stationnement et la congestion des ponts", communityEn: "cultural organizations, recreation programs, studios and inclusive fitness groups", communityFr: "les organismes culturels, programmes récréatifs, studios et groupes de conditionnement inclusif" },
  terrebonne: { name: "Terrebonne", areaEn: "Terrebonne, Lachenaie, La Plaine and nearby Lanaudière communities", areaFr: "Terrebonne, Lachenaie, La Plaine et les communautés voisines de Lanaudière", travelEn: "Autoroutes 25, 40 and 640, local roads, limited transit options and winter weather", travelFr: "les autoroutes 25, 40 et 640, les routes locales, les options de transport limitées et l’hiver", communityEn: "municipal recreation, dance and movement studios, schools and community associations", communityFr: "les loisirs municipaux, studios de danse et de mouvement, écoles et associations communautaires" },
  "pointe-claire": { name: "Pointe-Claire", areaEn: "Pointe-Claire and the wider West Island", areaFr: "Pointe-Claire et l’ensemble de l’Ouest-de-l’Île", travelEn: "Autoroutes 20 and 40, Saint-Jean Boulevard, buses, adapted transit and winter roads", travelFr: "les autoroutes 20 et 40, le boulevard Saint-Jean, les autobus, le transport adapté et les routes hivernales", communityEn: "West Island recreation centres, studios, schools and accessible sport organizations", communityFr: "les centres récréatifs, studios, écoles et organismes de sport adapté de l’Ouest-de-l’Île" },
};

export function getMovementTherapyLocalSections(city: CityKey, locale: Locale): MontrealPageContent["sections"] {
  const detail = cityDetails[city];
  if (locale === "fr-CA") {
    return [
      { heading: `La thérapie par le mouvement dans le quotidien à ${detail.name}`, paragraphs: [`Les personnes de ${detail.areaFr} n’abordent pas toutes le mouvement avec les mêmes capacités, objectifs ou contraintes. Une activité utile peut comprendre la danse, l’équilibre, la mobilité, des exercices rythmiques, un jeu actif ou un entraînement adapté, selon l’âge, l’énergie et les recommandations professionnelles de la personne. Le concept de The Silver Guardian met l’accent sur des possibilités artistiques et compétitives motivantes; il ne constitue ni un traitement médical ni un service clinique offert actuellement à ${detail.name}.`, `Le contexte local influence la participation. ${detail.travelFr} peuvent rendre une séance régulière difficile pour une famille qui concilie déjà l’école, le travail, les rendez-vous et les responsabilités de proche aidant. Une future initiative communautaire devrait donc envisager des horaires souples, des lieux accessibles, des formats plus courts et, lorsque cela convient, des activités pouvant être adaptées à la maison ou dans un milieu communautaire.`] },
      { heading: `Bâtir des liens responsables autour du mouvement à ${detail.name}`, paragraphs: [`${detail.communityFr} peuvent apporter une connaissance pratique des espaces, de l’équipement, des horaires et des obstacles à la participation. Leur implication éventuelle devrait commencer par des rôles précis et des renseignements publics exacts. Une présentation ou une conversation ne signifie pas qu’un programme, un partenaire ou une date est confirmé. The Silver Guardian devrait publier les détails seulement lorsque l’encadrement, l’accessibilité, la sécurité et les responsabilités sont clairement établis.`, `Toute activité décrite comme thérapie par le mouvement doit respecter les limites de la personne et l’expertise appropriée. The Silver Guardian ne possède, n’exploite, ne gère, ne dirige et ne représente aucun hôpital ni fournisseur de soins. Les décisions médicales, la réadaptation et les recommandations d’exercice appartiennent à la personne, à sa famille et aux professionnels qualifiés. Le rôle communautaire envisagé consiste à soutenir la motivation et l’accès, sans remplacer les soins ni laisser croire à une affiliation hospitalière.`] },
    ];
  }

  return [
    { heading: `Movement therapy in everyday life in ${detail.name}`, paragraphs: [`People across ${detail.areaEn} do not approach movement with the same abilities, goals or constraints. A useful activity might involve dance, balance, mobility, rhythmic exercise, active play or adapted training depending on a person’s age, energy and professional guidance. The Silver Guardian concept emphasizes motivating artistic and competitive opportunities; it is not medical treatment and no clinical movement therapy service is currently offered by the organization in ${detail.name}.`, `Local context affects participation. ${detail.travelEn} can make a regular session difficult for a family already coordinating school, employment, appointments and caregiving. A future community initiative should therefore consider flexible scheduling, accessible locations, shorter formats and, when appropriate, activities that can be adapted for home or community settings.`] },
    { heading: `Building responsible movement relationships in ${detail.name}`, paragraphs: [`${detail.communityEn} can contribute practical knowledge about spaces, equipment, scheduling and barriers to participation. Any future involvement should begin with defined roles and accurate public information. An introduction or conversation does not mean a program, partner or date is confirmed. The Silver Guardian should publish details only after supervision, accessibility, safety and responsibilities are clearly established.`, `Any activity described as movement therapy must respect the participant’s limits and appropriate professional expertise. The Silver Guardian does not own, operate, manage, direct or represent any hospital or healthcare provider. Medical decisions, rehabilitation and exercise recommendations belong to the participant, family and qualified professionals. The contemplated community role is to support motivation and access without replacing care or implying a hospital affiliation.`] },
  ];
}
