import type { Locale } from "@/lib/i18n";
import { getQuebecCityLinks } from "@/lib/quebecCityLinks";
import {
  getMontrealTopicContent,
  montrealLandingContent,
  montrealTopicSlugs,
  type MontrealPageContent,
  type MontrealTopicSlug,
} from "@/lib/montrealContent";

export const pointeClaireTopicSlugs = montrealTopicSlugs;
export type PointeClaireTopicSlug = MontrealTopicSlug;

function localizeText(value: string) {
  return value
    .replaceAll("Greater Montreal", "Pointe-Claire and the West Island")
    .replaceAll("Grand Montréal", "Pointe-Claire et l’Ouest-de-l’Île")
    .replaceAll("Montreal", "Pointe-Claire")
    .replaceAll("Montréal", "Pointe-Claire")
    .replaceAll("montreal", "pointe-claire")
    .replaceAll("montréalaise", "pointe-clairaise")
    .replaceAll("montréalais", "pointe-clairais");
}

function transformContent(content: MontrealPageContent): MontrealPageContent {
  return {
    ...content,
    title: localizeText(content.title), description: localizeText(content.description), keywords: content.keywords.map(localizeText),
    eyebrow: localizeText(content.eyebrow), heading: localizeText(content.heading), introduction: localizeText(content.introduction),
    imageLabel: localizeText(content.imageLabel), imageAlt: localizeText(content.imageAlt),
    supportingImages: content.supportingImages?.map((image) => ({ label: localizeText(image.label), alt: localizeText(image.alt) })),
    sections: content.sections.map((section) => ({ heading: localizeText(section.heading), paragraphs: section.paragraphs.map(localizeText), bullets: section.bullets?.map(localizeText) })),
    relatedHeading: localizeText(content.relatedHeading),
    relatedLinks: content.relatedLinks.filter((link) => !["/laval/", "/longueuil/", "/brossard/", "/terrebonne/", "/pointe-claire/"].includes(link.href)).map((link) => ({ href: link.href.replace("/montreal/", "/pointe-claire/"), label: localizeText(link.label), description: localizeText(link.description) })),
    faqHeading: localizeText(content.faqHeading), faqs: content.faqs.map((faq) => ({ question: localizeText(faq.question), answer: localizeText(faq.answer) })),
    closingHeading: localizeText(content.closingHeading), closingText: localizeText(content.closingText), ctaLabel: content.ctaLabel, ctaHref: content.ctaHref,
  };
}

const localSections: Record<PointeClaireTopicSlug, Record<Locale, MontrealPageContent["sections"]>> = {
  "pediatric-cancer": {
    en: [
      { heading: "Pediatric cancer support for Pointe-Claire families", paragraphs: ["A Pointe-Claire family may travel east from the West Island for specialized pediatric appointments while continuing to coordinate school, employment, sibling care and recovery at home. Autoroutes 20 and 40, Saint-Jean Boulevard, Lakeshore Road and changing traffic conditions can all shape the day. Winter snow, construction and a child’s fluctuating energy may make a familiar route unexpectedly difficult. Community support should account for that uncertainty instead of asking every family to attend at one fixed time or distant location.", "Pointe-Claire’s French- and English-speaking communities make bilingual communication a basic part of responsible planning. Local businesses, schools, recreation organizations, cultural groups and hockey associations can help accurate information reach families across the West Island. Their role is to support awareness, practical logistics and community relationships. Diagnosis, cancer treatment, medical advice and referrals must always remain with qualified pediatric professionals and the child’s family." ] },
      { heading: "Turning West Island support into practical action", paragraphs: ["A local organization can begin by reviewing The Silver Guardian’s stated facility and wish goals, then selecting one contribution it can maintain. It might share verified campaign details, make a fundraising activity more accessible or introduce someone with relevant transportation, event or family-service experience. A defined role is more useful than a broad promise while the care facility remains a concept and no Pointe-Claire clinical program, location, partner or opening date has been announced.", "Supporters can assess progress by asking how funds connect to the stated pediatric vision, what privacy protections are planned and which milestones are complete. They can also ask how treatment changes, mobility, winter travel and language preferences will affect participation. Clear published answers allow families to distinguish confirmed opportunities from developing ideas. For a household managing pediatric cancer, precise information protects limited time, personal information and emotional expectations." ] },
    ],
    "fr-CA": [
      { heading: "Le soutien au cancer pédiatrique pour les familles de Pointe-Claire", paragraphs: ["Une famille de Pointe-Claire peut se déplacer vers l’est depuis l’Ouest-de-l’Île pour des rendez-vous pédiatriques spécialisés tout en coordonnant l’école, le travail, la fratrie et le rétablissement à la maison. Les autoroutes 20 et 40, le boulevard Saint-Jean, le chemin du Bord-du-Lac et la circulation influencent la journée. La neige, les travaux et l’énergie changeante de l’enfant peuvent rendre un trajet familier difficile. L’appui communautaire devrait reconnaître cette incertitude plutôt qu’imposer une heure ou un lieu éloigné.", "Les communautés francophones et anglophones de Pointe-Claire font des communications bilingues une base de la planification. Les entreprises, écoles, organismes récréatifs, groupes culturels et associations de hockey peuvent diffuser une information exacte dans l’Ouest-de-l’Île. Leur rôle concerne la sensibilisation, la logistique et les relations communautaires. Le diagnostic, les traitements, les conseils médicaux et les recommandations demeurent la responsabilité des professionnels pédiatriques qualifiés et de la famille." ] },
      { heading: "Transformer l’appui de l’Ouest-de-l’Île en action", paragraphs: ["Un organisme local peut d’abord étudier les objectifs d’établissement et de souhaits de The Silver Guardian, puis choisir une contribution durable. Il peut diffuser les renseignements vérifiés, améliorer l’accessibilité d’une activité de financement ou présenter une personne expérimentée en transport, en événements ou en services familiaux. Un rôle défini vaut mieux qu’une promesse générale puisque l’établissement demeure un concept et qu’aucun programme clinique, emplacement, partenaire ou calendrier d’ouverture à Pointe-Claire n’est annoncé.", "Les gens peuvent demander comment les fonds servent la vision, quelles protections de la vie privée sont prévues et quelles étapes sont terminées. Ils peuvent aussi vérifier l’effet des changements de traitement, de la mobilité, de l’hiver et des préférences linguistiques sur la participation. Des réponses publiées distinguent les possibilités confirmées des idées en développement et protègent le temps, les renseignements et les attentes des familles." ] },
    ],
  },
  "hockey-themed-wishes": {
    en: [
      { heading: "A hockey wish connected to Pointe-Claire", paragraphs: ["Hockey in Pointe-Claire is experienced through local arenas, minor-hockey programs, schools, outdoor skating and family traditions shared across the West Island. One child may want to skate, while another cares about a jersey, equipment, team history or watching a game with relatives. A meaningful wish begins by understanding that child’s personal connection to hockey. It should not begin with a predetermined venue, publicity plan or assumption that every young fan wants the same type of event.", "West Island travel affects what is comfortable. A family may use Autoroute 20 or 40, travel along Saint-Jean Boulevard or continue east for treatment. Fatigue, snow, traffic, mobility equipment and infection precautions can change a plan quickly. A shorter experience close to home, a calm indoor alternative or an adapted hockey activity may be more valuable than a large event when it reduces strain and reflects what the child actually enjoys." ] },
      { heading: "Building local hockey relationships before promising a wish", paragraphs: ["A responsible wish needs a defined participant process, family consent, relevant care guidance, accessible logistics, budget and contingency planning and partners who understand their responsibilities. Pointe-Claire hockey organizations, arena communities, schools, recreation leaders and businesses may each offer useful knowledge. An introduction is not confirmation, however. No date, participant, player appearance or specific experience should be promoted until the essential pieces are secured.", "The Silver Guardian’s 32 Wishes in 32 Cities goal gives West Island relationship-building a clear direction. Supporters can explain the initiative accurately, identify bilingual, travel and accessibility needs and make qualified introductions without implying that applications are open. If a wish is confirmed, the child and family should control privacy and public participation. That discipline keeps the experience centred on the child rather than on the organizations involved." ] },
    ],
    "fr-CA": [
      { heading: "Un souhait de hockey lié à Pointe-Claire", paragraphs: ["À Pointe-Claire, le hockey se vit dans les arénas locaux, les programmes mineurs, les écoles, les patinoires extérieures et les traditions familiales de l’Ouest-de-l’Île. Un enfant peut vouloir patiner; un autre préfère un chandail, l’équipement, l’histoire d’une équipe ou un match avec ses proches. Un souhait significatif commence par le lien personnel de l’enfant avec le hockey, et non par un lieu, une stratégie publicitaire ou l’idée que tous les jeunes partisans veulent le même événement.", "Les déplacements dans l’Ouest-de-l’Île influencent le confort. Une famille peut emprunter l’autoroute 20 ou 40, le boulevard Saint-Jean ou continuer vers l’est pour les traitements. La fatigue, la neige, la circulation, la mobilité et les précautions peuvent changer le plan. Une expérience plus courte près du domicile, une option calme à l’intérieur ou une activité adaptée peut offrir davantage lorsqu’elle réduit les efforts et respecte les intérêts de l’enfant." ] },
      { heading: "Bâtir les relations de hockey avant de faire une promesse", paragraphs: ["Un souhait responsable exige un processus défini, le consentement familial, des indications de soins pertinentes, une logistique accessible, un budget, des solutions de rechange et des partenaires aux rôles clairs. Les organismes de hockey, communautés d’aréna, écoles, responsables des loisirs et entreprises de Pointe-Claire peuvent apporter une connaissance utile. Une présentation ne constitue toutefois pas une confirmation; il ne faut annoncer ni date, ni participant, ni joueur, ni expérience avant d’avoir assuré les éléments essentiels.", "L’objectif 32 souhaits dans 32 villes donne une direction au travail dans l’Ouest-de-l’Île. Les gens peuvent expliquer fidèlement l’initiative, cerner les besoins bilingues, de déplacement et d’accessibilité et présenter des contacts sans laisser croire que les demandes sont ouvertes. Si un souhait est confirmé, l’enfant et la famille devraient contrôler la vie privée et la participation publique." ] },
    ],
  },
  "hospital-wishes": {
    en: [
      { heading: "Hospital wishes for Pointe-Claire families", paragraphs: ["A child from Pointe-Claire receiving specialized pediatric care may spend considerable time travelling east and back to the West Island. The day can involve highway traffic, parking or transit, waiting and recovery before the family returns home. A supportive wish should fit around the clinical schedule instead of competing with it. Flexible timing, a clear cancellation approach and an alternate format reduce pressure when an appointment runs late or the child unexpectedly needs rest.", "A local element may make it easier for siblings and caregivers to participate, but the nearest Pointe-Claire venue is not automatically the best choice. The child may prefer an opportunity elsewhere, or care guidance may require a quieter setting. Organizers should ask what is safe, accessible and personally meaningful rather than measuring the value of a wish by distance, audience size or public attention." ] },
      { heading: "Permission, privacy and honest referral information", paragraphs: ["Hospital-connected wishes require formal permission and coordination. Infection-control precautions, visitor limits, food restrictions, photography policies and mobility needs can affect every detail. Families should never be asked to send medical records through ordinary email or social messages. A future referral process should explain eligibility, why information is collected, who can review it, expected response times and what happens when demand exceeds available opportunities.", "No Pointe-Claire referral process or hospital partnership is announced here. The Silver Guardian is developing community and hockey relationships for its broader wish goal, so this page provides information rather than accepting applications. Local advocates can prepare responsibly by understanding bilingual consent, privacy, accessibility and adaptable family logistics. These safeguards do not reduce generosity; they help a future experience earn trust and protect a child’s dignity." ] },
    ],
    "fr-CA": [
      { heading: "Des souhaits à l’hôpital pour les familles de Pointe-Claire", paragraphs: ["Un enfant de Pointe-Claire qui reçoit des soins pédiatriques spécialisés peut passer beaucoup de temps à se déplacer vers l’est puis à revenir dans l’Ouest-de-l’Île. La journée peut comprendre la circulation, le stationnement ou le transport collectif, l’attente et le rétablissement. Un souhait devrait s’adapter à l’horaire clinique plutôt que lui faire concurrence. Un horaire souple, des modalités d’annulation claires et un autre format réduisent la pression lorsqu’un rendez-vous se prolonge ou que l’enfant doit se reposer.", "Un élément local peut faciliter la participation de la fratrie et des proches, mais le lieu de Pointe-Claire le plus proche n’est pas automatiquement le meilleur. L’enfant peut préférer une possibilité ailleurs, ou les consignes de soins peuvent exiger un milieu calme. Les organisateurs devraient privilégier la sécurité, l’accessibilité et la signification personnelle plutôt que la distance, la foule ou l’attention publique." ] },
      { heading: "Autorisations, vie privée et information honnête", paragraphs: ["Les souhaits liés à l’hôpital exigent des autorisations et une coordination formelles. Les précautions contre les infections, les limites de visiteurs, l’alimentation, la photographie et la mobilité influencent chaque détail. Une famille ne devrait jamais transmettre un dossier médical par courriel ordinaire ou message social. Un futur processus devrait expliquer l’admissibilité, la collecte, l’accès aux renseignements, les délais et la gestion d’une demande supérieure aux possibilités.", "Aucun processus de demande ni partenariat hospitalier à Pointe-Claire n’est annoncé ici. The Silver Guardian développe des relations pour son objectif élargi; la page informe sans recevoir de demandes. Les défenseurs locaux peuvent comprendre le consentement bilingue, la vie privée, l’accessibilité et la logistique familiale adaptable. Ces protections gagnent la confiance et respectent la dignité de l’enfant." ] },
    ],
  },
  "childrens-hospital": {
    en: [
      { heading: "What West Island families may need from pediatric care", paragraphs: ["Pointe-Claire families may receive some services close to home while travelling east or elsewhere in the region for specialized pediatric care. Any future facility concept should understand that care pathway before defining what it would add. Autoroutes 20 and 40, local and adapted transportation, winter access, caregiver schedules, language needs and coordination with established providers are operational questions that a hockey theme or building image cannot answer alone.", "The Silver Guardian currently describes a child-friendly, hockey-themed pediatric care vision, not an operating children’s hospital. No Pointe-Claire location, construction timeline, clinical team or service list has been announced. Clear language about that stage helps families avoid mistaking a fundraising concept for available care and gives potential community partners an accurate basis for evaluating progress." ] },
      { heading: "Planning an accessible facility for Pointe-Claire", paragraphs: ["Pointe-Claire includes residential neighbourhoods, commercial corridors and lakeside areas with different travel patterns. A credible location study would need to consider highway access, public transit, winter maintenance, accessible drop-off, family parking and travel from other West Island communities. Public information and wayfinding should be clear in French and English, with appropriate support for families who communicate in other languages.", "Inside a future facility, hockey imagery should support comfort and orientation without overwhelming children with sensory needs or excluding those who do not follow the sport. Calm areas, accessible circulation, caregiver space, adolescent privacy and infection prevention must guide design choices. Children, families, accessibility professionals and qualified health leaders should influence planning before decorative concepts or facility claims are treated as final." ] },
    ],
    "fr-CA": [
      { heading: "Ce dont les familles de l’Ouest-de-l’Île peuvent avoir besoin", paragraphs: ["Les familles de Pointe-Claire peuvent recevoir certains services près du domicile tout en se déplaçant vers l’est ou ailleurs pour des soins pédiatriques spécialisés. Tout futur concept devrait comprendre ce parcours avant de définir son apport. Les autoroutes 20 et 40, le transport local et adapté, l’accès hivernal, les horaires des proches, les besoins linguistiques et la coordination avec les services établis sont des questions auxquelles un thème de hockey ou une image de bâtiment ne répond pas seul.", "The Silver Guardian décrit actuellement une vision de soins adaptée aux enfants et inspirée du hockey, et non un hôpital en activité. Aucun emplacement, calendrier de construction, équipe clinique ou ensemble de services à Pointe-Claire n’est annoncé. Cette précision évite de confondre le financement avec des soins disponibles et donne aux partenaires une base exacte pour évaluer les progrès." ] },
      { heading: "Planifier un établissement accessible à Pointe-Claire", paragraphs: ["Pointe-Claire comprend des quartiers résidentiels, des axes commerciaux et des secteurs riverains aux habitudes de déplacement différentes. Une étude crédible devrait considérer l’accès autoroutier, le transport collectif, l’entretien hivernal, un débarcadère accessible, le stationnement familial et les déplacements des autres communautés de l’Ouest-de-l’Île. L’information et l’orientation devraient être claires en français et en anglais, avec un soutien approprié pour d’autres langues.", "Dans un futur établissement, les images de hockey devraient améliorer le confort et l’orientation sans surcharger les enfants ayant des besoins sensoriels ni exclure ceux qui ne suivent pas ce sport. Les zones calmes, la circulation accessible, l’espace des proches, l’intimité des adolescents et la prévention des infections doivent guider le design. Les enfants, familles et experts qualifiés devraient influencer le plan." ] },
    ],
  },
};

export const pointeClaireLandingContent: Record<Locale, MontrealPageContent> = {
  en: {
    ...transformContent(montrealLandingContent.en), title: "Pediatric Care Support in Pointe-Claire", description: "Explore The Silver Guardian’s Pointe-Claire vision for pediatric care support, hockey wishes and community fundraising.", eyebrow: "Pointe-Claire, Quebec", heading: "Pediatric care and hockey-inspired hope in Pointe-Claire", introduction: "Pointe-Claire families facing pediatric cancer or heart disease may balance regional treatment with school, work, West Island travel and everyday family life. The Silver Guardian’s vision gives residents, businesses and hockey groups a way to explore support for a child-friendly care concept and hockey-related wishes.",
    sections: [
      { heading: "A mission connected to Pointe-Claire", paragraphs: ["Pointe-Claire’s neighbourhood, school, recreation, cultural and business networks connect French- and English-speaking families across the West Island. Those relationships can help a clearly defined pediatric support mission reach people without suggesting that an operating program already exists.", "The Silver Guardian is gathering support for a proposed hockey-themed pediatric care environment and its 32 Wishes in 32 Cities goal. No Pointe-Claire facility, clinical service, partner or event date is announced here."], bullets: ["A child-friendly pediatric care concept inspired by hockey", "A focus primarily on pediatric cancer and heart disease", "Community fundraising and relationship-building for future progress"] },
      { heading: "Why West Island context matters", paragraphs: ["Families may use Autoroutes 20 and 40, Saint-Jean Boulevard or other local connections for specialized appointments. Winter roads, traffic, accessibility and bilingual communication should shape future activities. Responsible planning begins with the family’s actual journey."] },
      { heading: "How to explore the initiative", paragraphs: ["Use the focused Pointe-Claire resources below, review the current fundraising and wishes goals and follow verified progress. Useful support grows through clear roles and confirmed milestones rather than assumptions about unavailable services."] },
    ], relatedHeading: "Explore the Pointe-Claire initiative",
    relatedLinks: [...transformContent(montrealLandingContent.en).relatedLinks.filter((link) => link.href.startsWith("/pointe-claire/") && link.href !== "/pointe-claire/"), ...getQuebecCityLinks("en", "pointe-claire")],
  },
  "fr-CA": {
    ...transformContent(montrealLandingContent["fr-CA"]), title: "Soutien aux soins pédiatriques à Pointe-Claire", description: "Découvrez la vision pointe-clairaise de The Silver Guardian : soins pédiatriques, souhaits de hockey et financement communautaire.", eyebrow: "Pointe-Claire, Québec", heading: "Des soins pédiatriques et de l’espoir inspiré du hockey à Pointe-Claire", introduction: "Les familles de Pointe-Claire touchées par le cancer ou une maladie cardiaque pédiatrique peuvent concilier les traitements régionaux, l’école, le travail, les déplacements dans l’Ouest-de-l’Île et la vie familiale. La vision de The Silver Guardian permet aux résidents, entreprises et groupes de hockey d’explorer un appui.",
    sections: [
      { heading: "Une mission liée à Pointe-Claire", paragraphs: ["Les réseaux de quartier, scolaires, récréatifs, culturels et commerciaux de Pointe-Claire relient les familles francophones et anglophones de l’Ouest-de-l’Île. Ces relations peuvent faire connaître une mission pédiatrique précise sans laisser croire qu’un programme fonctionne déjà.", "The Silver Guardian mobilise un appui pour un milieu de soins proposé sur le thème du hockey et son objectif 32 souhaits dans 32 villes. Aucun établissement, service clinique, partenaire ou événement pointe-clairais n’est annoncé ici."], bullets: ["Un concept de soins adapté aux enfants et inspiré du hockey", "Une attention surtout au cancer et aux maladies cardiaques pédiatriques", "Du financement et des relations communautaires pour de futurs progrès"] },
      { heading: "Pourquoi le contexte de l’Ouest-de-l’Île compte", paragraphs: ["Les familles peuvent utiliser les autoroutes 20 et 40, le boulevard Saint-Jean ou d’autres liaisons pour des rendez-vous spécialisés. Les routes hivernales, la circulation, l’accessibilité et les communications bilingues devraient orienter les futures activités."] },
      { heading: "Comment découvrir l’initiative", paragraphs: ["Consultez les ressources de Pointe-Claire ci-dessous, découvrez les objectifs actuels et suivez les progrès vérifiés. Un appui utile repose sur des rôles clairs et des étapes confirmées plutôt que sur des services non disponibles."] },
    ], relatedHeading: "Découvrir l’initiative pointe-clairaise",
    relatedLinks: [...transformContent(montrealLandingContent["fr-CA"]).relatedLinks.filter((link) => link.href.startsWith("/pointe-claire/") && link.href !== "/pointe-claire/"), ...getQuebecCityLinks("fr-CA", "pointe-claire")],
  },
};

export function getPointeClaireTopicContent(slug: string, locale: Locale) {
  if (!pointeClaireTopicSlugs.includes(slug as PointeClaireTopicSlug)) return undefined;
  const source = getMontrealTopicContent(slug, locale); if (!source) return undefined;
  const content = transformContent(source);
  return { ...content, sections: [...localSections[slug as PointeClaireTopicSlug][locale], ...content.sections] };
}
