import type { Locale } from "@/lib/i18n";
import { getMovementTherapyLocalSections } from "@/lib/movementTherapyGeoContent";
import { getQuebecCityLinks } from "@/lib/quebecCityLinks";
import {
  getMontrealTopicContent,
  montrealLandingContent,
  montrealTopicSlugs,
  type MontrealPageContent,
  type MontrealTopicSlug,
} from "@/lib/montrealContent";

export const terrebonneTopicSlugs = montrealTopicSlugs;
export type TerrebonneTopicSlug = MontrealTopicSlug;

function localizeText(value: string) {
  return value
    .replaceAll("Greater Montreal", "Terrebonne and the North Shore")
    .replaceAll("Grand Montréal", "Terrebonne et la Rive-Nord")
    .replaceAll("Montreal", "Terrebonne")
    .replaceAll("Montréal", "Terrebonne")
    .replaceAll("montreal", "terrebonne")
    .replaceAll("montréalaise", "terrebonnienne")
    .replaceAll("montréalais", "terrebonnien");
}

function transformContent(content: MontrealPageContent): MontrealPageContent {
  return {
    ...content,
    title: localizeText(content.title), description: localizeText(content.description), keywords: content.keywords.map(localizeText),
    eyebrow: localizeText(content.eyebrow), heading: localizeText(content.heading), introduction: localizeText(content.introduction),
    imageLabel: localizeText(content.imageLabel), imageAlt: localizeText(content.imageAlt),
    supportingImages: content.supportingImages?.map((image) => ({ label: localizeText(image.label), alt: localizeText(image.alt) })),
    sections: content.sections.map((section) => ({ heading: localizeText(section.heading), paragraphs: section.paragraphs.map(localizeText), bullets: section.bullets?.map(localizeText) })),
    relatedHeading: localizeText(content.relatedHeading),
    relatedLinks: content.relatedLinks.filter((link) => !["/laval/", "/longueuil/", "/brossard/", "/terrebonne/"].includes(link.href)).map((link) => ({ href: link.href.replace("/montreal/", "/terrebonne/"), label: localizeText(link.label), description: localizeText(link.description) })),
    faqHeading: localizeText(content.faqHeading), faqs: content.faqs.map((faq) => ({ question: localizeText(faq.question), answer: localizeText(faq.answer) })),
    closingHeading: localizeText(content.closingHeading), closingText: localizeText(content.closingText), ctaLabel: content.ctaLabel, ctaHref: content.ctaHref,
  };
}

const localSections: Record<TerrebonneTopicSlug, Record<Locale, MontrealPageContent["sections"]>> = {
  "pediatric-cancer": {
    en: [
      { heading: "Pediatric cancer support across Terrebonne", paragraphs: ["Families in Terrebonne, Lachenaie and La Plaine may travel beyond their immediate community for specialized pediatric appointments while continuing to manage school, work, sibling care and recovery at home. Routes can involve Autoroutes 25, 40 and 640, connections through Laval or Montreal and changing North Shore winter conditions. Traffic, snow and a child’s energy can turn a familiar drive into a difficult day. Community support should acknowledge that uncertainty instead of requiring every family to meet the same fixed schedule.", "A Terrebonne-focused initiative can respond with flexible participation, accessible local options and clear communication in French and English. Businesses, neighbourhood organizations, recreation groups and hockey associations can help reliable information travel through Lanaudière and North Shore networks. Their role is to strengthen awareness, logistics and relationships. Diagnosis, treatment, referrals and health decisions must remain with the family and qualified pediatric professionals." ] },
      { heading: "From North Shore awareness to practical action", paragraphs: ["A local organization can start by studying The Silver Guardian’s stated care and wish goals and selecting one contribution it can sustain. It might share verified campaign details, support an accessible fundraising activity or introduce organizers to someone with relevant transportation, event or family-service experience. A defined commitment is more useful than a broad promise while the community initiatives remain in development and no Terrebonne clinical program, partner site or opening date has been announced.", "Supporters should look for milestones that answer local questions: how will treatment changes affect participation, what travel and accessibility barriers have been considered, how will privacy be protected and how do funds connect to the stated pediatric mission? Published answers allow families to distinguish a confirmed opportunity from a developing idea. For a household facing pediatric cancer, precise information protects limited time, personal data and emotional expectations." ] },
    ],
    "fr-CA": [
      { heading: "Le soutien au cancer pédiatrique partout à Terrebonne", paragraphs: ["Les familles de Terrebonne, Lachenaie et La Plaine peuvent devoir quitter leur communauté pour des rendez-vous pédiatriques spécialisés tout en maintenant l’école, le travail, la fratrie et le rétablissement à la maison. Les trajets peuvent emprunter les autoroutes 25, 40 et 640, passer par Laval ou Montréal et subir l’hiver de la Rive-Nord. La circulation, la neige et l’énergie de l’enfant transforment parfois un trajet familier en journée difficile. L’appui communautaire devrait reconnaître cette incertitude plutôt qu’imposer un horaire identique à tous.", "Une initiative terrebonnienne peut offrir une participation souple, des options locales accessibles et des communications claires en français et en anglais. Les entreprises, organismes de quartier, groupes récréatifs et associations de hockey peuvent diffuser de l’information fiable dans Lanaudière et sur la Rive-Nord. Leur rôle concerne la sensibilisation, la logistique et les relations. Les diagnostics, traitements, recommandations et décisions de santé demeurent la responsabilité de la famille et des professionnels qualifiés." ] },
      { heading: "De la sensibilisation sur la Rive-Nord à l’action", paragraphs: ["Un organisme local peut étudier les objectifs de soins et de souhaits de The Silver Guardian, puis choisir une contribution durable. Il peut diffuser les renseignements vérifiés, soutenir une activité accessible ou présenter une personne expérimentée en transport, en événements ou en services familiaux. Un engagement défini vaut mieux qu’une promesse générale puisque les initiatives communautaires demeurent en développement et qu’aucun programme clinique, site partenaire ou calendrier d’ouverture à Terrebonne n’est annoncé.", "Les prochaines étapes devraient répondre aux questions locales : comment les changements de traitement influenceront-ils la participation, quels obstacles de déplacement et d’accessibilité sont prévus, comment la vie privée sera-t-elle protégée et comment les fonds serviront-ils la mission? Des réponses publiées distinguent une possibilité confirmée d’une idée en développement. Cette précision protège le temps, les données et les attentes des familles." ] },
    ],
  },
  "hockey-themed-wishes": {
    en: [
      { heading: "A hockey wish connected to life in Terrebonne", paragraphs: ["Hockey in Terrebonne grows through minor-hockey organizations, municipal arenas, schools, outdoor rinks and family traditions in Terrebonne, Lachenaie and La Plaine. One child may dream of skating, while another is interested in a jersey, equipment, team history or sharing a game with relatives. A meaningful wish begins with the child’s own connection to hockey. It should not begin with a predetermined arena, publicity plan or assumption that every young fan wants the same format.", "North Shore geography affects what is comfortable. A family may travel along Autoroute 640, connect to Autoroutes 25 or 40 or continue toward Laval or Montreal for treatment. Fatigue, winter roads, mobility equipment and infection precautions may change the plan. A shorter local activity, a calm indoor alternative or an experience adapted around the child can be more meaningful than a larger event when it reduces strain and reflects a personal interest." ] },
      { heading: "Building relationships before announcing a wish", paragraphs: ["A responsible wish requires a defined participant process, family consent, relevant guidance from the child’s care team, accessible logistics, budget and contingency planning and partners who understand their responsibilities. Local hockey groups, arena communities, businesses and recreation leaders may offer valuable knowledge, but an introduction is not confirmation. Dates, participants, player appearances and specific experiences should not be promoted until the essential elements are secured.", "The Silver Guardian’s 32 Wishes in 32 Cities goal gives Terrebonne relationship-building a clear direction. Supporters can explain the goal accurately, identify travel, language and accessibility questions and make qualified introductions without implying that applications are open. If a wish is eventually confirmed, the family should control privacy and public participation. That discipline helps community enthusiasm become a safe experience centred on the child rather than on participating organizations." ] },
    ],
    "fr-CA": [
      { heading: "Un souhait de hockey lié à la vie de Terrebonne", paragraphs: ["À Terrebonne, le hockey se développe dans les organismes mineurs, les arénas municipaux, les écoles, les patinoires extérieures et les traditions familiales de Terrebonne, Lachenaie et La Plaine. Un enfant peut rêver de patiner; un autre préfère un chandail, l’équipement, l’histoire d’une équipe ou un match avec ses proches. Un souhait significatif commence par le lien personnel de l’enfant avec le hockey, et non par un aréna, une stratégie publicitaire ou un format déjà choisi.", "La géographie de la Rive-Nord influence le confort. Une famille peut emprunter l’autoroute 640, rejoindre les autoroutes 25 ou 40 ou continuer vers Laval ou Montréal pour les traitements. La fatigue, les routes hivernales, la mobilité et les précautions contre les infections peuvent changer le plan. Une activité locale plus courte, une option calme à l’intérieur ou une expérience adaptée peut avoir davantage de sens lorsqu’elle réduit les efforts et respecte l’intérêt de l’enfant." ] },
      { heading: "Bâtir les relations avant d’annoncer un souhait", paragraphs: ["Un souhait responsable exige un processus défini, le consentement familial, des indications pertinentes de l’équipe de soins, une logistique accessible, un budget, des solutions de rechange et des partenaires qui comprennent leur rôle. Les groupes de hockey, communautés d’aréna, entreprises et responsables des loisirs peuvent apporter une connaissance utile, mais une présentation ne constitue pas une confirmation. Il ne faut annoncer ni date, ni participant, ni joueur, ni expérience avant d’avoir assuré les éléments essentiels.", "L’objectif 32 souhaits dans 32 villes donne une direction claire aux relations de Terrebonne. Les gens peuvent expliquer fidèlement le but, soulever les questions de déplacement, de langue et d’accessibilité et présenter des contacts sans laisser croire que les demandes sont ouvertes. Si un souhait est confirmé, la famille devrait contrôler la vie privée et la participation publique. Cette rigueur garde l’expérience centrée sur l’enfant." ] },
    ],
  },
  "hospital-wishes": {
    en: [
      { heading: "Hospital wishes for families travelling from Terrebonne", paragraphs: ["A Terrebonne child receiving specialized pediatric care may spend significant time travelling through the North Shore and into Laval or Montreal. The day can include highways, bridge connections, parking, waiting and recovery before the family returns home. A supportive wish should work around the clinical schedule rather than compete with it. Flexible timing, a clear cancellation process and an alternate format reduce pressure when an appointment changes or the child needs unexpected rest.", "A local Terrebonne element may sometimes make it easier for siblings and caregivers to participate, but the closest venue is not automatically the right one. The child may prefer an opportunity elsewhere, or care guidance may require a quieter setting. Organizers should ask what is safe, accessible and personally meaningful rather than measuring a wish by travel distance, audience size or public visibility." ] },
      { heading: "Permission, privacy and referral boundaries", paragraphs: ["Hospital-connected activity requires formal permission and coordination. Infection-control precautions, visitor limits, food restrictions, photography policies and mobility needs may shape every detail. Families should never be asked to send medical records through an ordinary message. Any future referral process should state who may apply, why information is collected, who can access it, expected response times and what happens if demand exceeds capacity.", "No Terrebonne referral process or hospital partnership is announced here. The Silver Guardian is building community and hockey relationships for its broader wish goal, so this page provides information rather than accepting applications. Local advocates can still prepare by learning about bilingual consent, accessibility, secure information handling and adaptable family logistics. Those safeguards are how a future experience earns confidence and protects a child’s dignity." ] },
    ],
    "fr-CA": [
      { heading: "Des souhaits pour les familles qui se déplacent depuis Terrebonne", paragraphs: ["Un enfant de Terrebonne qui reçoit des soins pédiatriques spécialisés peut passer beaucoup de temps à se déplacer sur la Rive-Nord puis vers Laval ou Montréal. La journée peut comprendre les autoroutes, les ponts, le stationnement, l’attente et le rétablissement avant le retour à la maison. Un souhait devrait respecter l’horaire clinique plutôt que lui faire concurrence. Un horaire souple, des modalités d’annulation claires et un autre format réduisent la pression lorsqu’un rendez-vous change ou que l’enfant doit se reposer.", "Un élément local peut parfois faciliter la participation de la fratrie et des proches, mais le lieu le plus près n’est pas automatiquement le meilleur. L’enfant peut préférer une possibilité ailleurs, ou les consignes de soins peuvent exiger un milieu calme. Les organisateurs devraient privilégier la sécurité, l’accessibilité et la signification personnelle plutôt que la distance, la foule ou la visibilité publique." ] },
      { heading: "Autorisations, vie privée et limites des demandes", paragraphs: ["Une activité liée à l’hôpital exige des autorisations et une coordination formelles. Les précautions contre les infections, les limites de visiteurs, l’alimentation, la photographie et la mobilité peuvent déterminer chaque détail. Une famille ne devrait jamais transmettre un dossier médical par un message ordinaire. Tout futur processus devrait expliquer qui peut faire une demande, pourquoi les renseignements sont recueillis, qui y accède, les délais et la gestion d’une demande supérieure à la capacité.", "Aucun processus de demande ni partenariat hospitalier à Terrebonne n’est annoncé ici. The Silver Guardian développe des relations pour son objectif élargi; la page informe sans recevoir de demandes. Les défenseurs locaux peuvent se préparer en comprenant le consentement bilingue, l’accessibilité, la sécurité des renseignements et la logistique familiale adaptable. Ces protections gagnent la confiance et respectent la dignité de l’enfant." ] },
    ],
  },
  "movement-therapy": {
    en: getMovementTherapyLocalSections("terrebonne", "en"),
    "fr-CA": getMovementTherapyLocalSections("terrebonne", "fr-CA"),
  },
};

export const terrebonneLandingContent: Record<Locale, MontrealPageContent> = {
  en: {
    ...transformContent(montrealLandingContent.en), title: "Pediatric Care Support in Terrebonne", description: "Explore The Silver Guardian’s Terrebonne vision for pediatric care support, hockey wishes and community fundraising.", eyebrow: "Terrebonne, Quebec", heading: "Pediatric care and hockey-inspired hope in Terrebonne", introduction: "Terrebonne families facing pediatric cancer or heart disease may balance regional treatment with school, work, North Shore travel and everyday life in Terrebonne, Lachenaie or La Plaine. The Silver Guardian’s vision gives residents, businesses and hockey groups a way to explore support for a independent movement and hockey-wish concepts.",
    sections: [
      { heading: "A mission connected to Terrebonne", paragraphs: ["Terrebonne, Lachenaie and La Plaine are connected through neighbourhood organizations, recreation, schools, businesses and hockey. Those networks can help a clearly defined pediatric support mission reach families without suggesting that an operating program already exists.", "The Silver Guardian is developing independent community fundraising, movement and wish initiatives. No Terrebonne movement program, wish event or healthcare affiliation is announced here."], bullets: ["Independent community support inspired by hockey and accessible movement", "A focus primarily on pediatric cancer and heart disease", "Community fundraising and relationship-building for future progress"] },
      { heading: "Why North Shore context matters", paragraphs: ["Families may use Autoroutes 25, 40 and 640 or travel through Laval and Montreal for specialized appointments. Winter roads, traffic, accessibility and bilingual communication should shape any future activity. Responsible planning begins with the family’s actual journey."] },
      { heading: "How to explore the initiative", paragraphs: ["Use the focused Terrebonne resources below, review the current fundraising and wishes goals and follow verified progress. Useful support grows through clear roles and confirmed milestones rather than assumptions about services that are not available."] },
    ], relatedHeading: "Explore the Terrebonne initiative",
    relatedLinks: [...transformContent(montrealLandingContent.en).relatedLinks.filter((link) => link.href.startsWith("/terrebonne/") && link.href !== "/terrebonne/"), ...getQuebecCityLinks("en", "terrebonne")],
  },
  "fr-CA": {
    ...transformContent(montrealLandingContent["fr-CA"]), title: "Soutien aux soins pédiatriques à Terrebonne", description: "Découvrez la vision terrebonnienne de The Silver Guardian : soins pédiatriques, souhaits de hockey et financement communautaire.", eyebrow: "Terrebonne, Québec", heading: "Des soins pédiatriques et de l’espoir inspiré du hockey à Terrebonne", introduction: "Les familles de Terrebonne touchées par le cancer ou une maladie cardiaque pédiatrique peuvent concilier les traitements régionaux, l’école, le travail, les déplacements sur la Rive-Nord et la vie à Terrebonne, Lachenaie ou La Plaine. La vision de The Silver Guardian permet d’explorer un appui communautaire.",
    sections: [
      { heading: "Une mission liée à Terrebonne", paragraphs: ["Terrebonne, Lachenaie et La Plaine sont reliées par les organismes de quartier, les loisirs, les écoles, les entreprises et le hockey. Ces réseaux peuvent faire connaître une mission pédiatrique précise sans laisser croire qu’un programme fonctionne déjà.", "The Silver Guardian développe des initiatives communautaires indépendantes de financement, de mouvement et de souhaits. Aucun programme de mouvement, événement de souhait ou lien avec un fournisseur de soins terrebonnien n’est annoncé ici."], bullets: ["Un soutien communautaire indépendant inspiré du hockey et du mouvement accessible", "Une attention surtout au cancer et aux maladies cardiaques pédiatriques", "Du financement et des relations communautaires pour de futurs progrès"] },
      { heading: "Pourquoi le contexte de la Rive-Nord compte", paragraphs: ["Les familles peuvent utiliser les autoroutes 25, 40 et 640 ou passer par Laval et Montréal pour des rendez-vous spécialisés. Les routes hivernales, la circulation, l’accessibilité et les communications bilingues devraient orienter les futures activités."] },
      { heading: "Comment découvrir l’initiative", paragraphs: ["Consultez les ressources de Terrebonne ci-dessous, découvrez les objectifs actuels et suivez les progrès vérifiés. Un appui utile repose sur des rôles clairs et des étapes confirmées plutôt que sur des services non disponibles."] },
    ], relatedHeading: "Découvrir l’initiative terrebonnienne",
    relatedLinks: [...transformContent(montrealLandingContent["fr-CA"]).relatedLinks.filter((link) => link.href.startsWith("/terrebonne/") && link.href !== "/terrebonne/"), ...getQuebecCityLinks("fr-CA", "terrebonne")],
  },
};

export function getTerrebonneTopicContent(slug: string, locale: Locale) {
  if (!terrebonneTopicSlugs.includes(slug as TerrebonneTopicSlug)) return undefined;
  const source = getMontrealTopicContent(slug, locale); if (!source) return undefined;
  const content = transformContent(source);
  return { ...content, sections: [...localSections[slug as TerrebonneTopicSlug][locale], ...content.sections] };
}
