project: the-silver-guardian

services:
  website:
    type: static
    path: .
    build: npm run build
    output: out
    spa: false
  api:
    type: node
    path: .
    start: node app.js
    healthcheck: /health
